// Code generated by tools/generate-protocol.mjs; DO NOT EDIT.

package v2

const ProtocolVersion = "2.0"
const ProtocolVersionNumber uint32 = 2
const SchemaVersion uint32 = 2
const MetricSemanticsVersion uint32 = 1
const DefaultMaxBatchEvents uint32 = 500
const DefaultMaxBatchBytes uint32 = 1048576

type UInt64String string
type DecimalString string
type HmacSha256 string
type Base64Url32 string

type EventType string

const (
	EventTypeModelUsageRecorded EventType = "model_usage_recorded"
	EventTypeCostRecorded       EventType = "cost_recorded"
	EventTypeSessionStarted     EventType = "session_started"
	EventTypeSessionEnded       EventType = "session_ended"
	EventTypeTurnStarted        EventType = "turn_started"
	EventTypeTurnCompleted      EventType = "turn_completed"
	EventTypeToolInvoked        EventType = "tool_invoked"
	EventTypeSkillInvoked       EventType = "skill_invoked"
	EventTypeCodeChanged        EventType = "code_changed"
)

type AckResult string

const (
	AckResultAccepted  AckResult = "accepted"
	AckResultDuplicate AckResult = "duplicate"
	AckResultDiscarded AckResult = "discarded"
	AckResultRetry     AckResult = "retry"
	AckResultBlocked   AckResult = "blocked"
	AckResultConflict  AckResult = "conflict"
	AckResultInvalid   AckResult = "invalid"
)

type Accuracy string

const (
	AccuracyExact      Accuracy = "exact"
	AccuracyDerived    Accuracy = "derived"
	AccuracyCorrelated Accuracy = "correlated"
	AccuracyEstimated  Accuracy = "estimated"
)

type TimeSource string

const (
	TimeSourceSourceRecord TimeSource = "source_record"
	TimeSourcePriorRecord  TimeSource = "prior_record"
	TimeSourceFileMtime    TimeSource = "file_mtime"
	TimeSourceUnknown      TimeSource = "unknown"
)

type CostSource string

const (
	CostSourceProviderReported CostSource = "provider_reported"
	CostSourceCalculatedPrice  CostSource = "calculated_price"
)

type TurnTrigger string

const (
	TurnTriggerUser      TurnTrigger = "user"
	TurnTriggerSystem    TurnTrigger = "system"
	TurnTriggerScheduled TurnTrigger = "scheduled"
	TurnTriggerSubagent  TurnTrigger = "subagent"
)

type SessionEndReason string

const (
	SessionEndReasonCompleted SessionEndReason = "completed"
	SessionEndReasonCancelled SessionEndReason = "cancelled"
	SessionEndReasonError     SessionEndReason = "error"
	SessionEndReasonTimeout   SessionEndReason = "timeout"
	SessionEndReasonUnknown   SessionEndReason = "unknown"
)

type AckErrorCode string

const (
	AckErrorCodeOutsideWindow      AckErrorCode = "outside_window"
	AckErrorCodeDeleted            AckErrorCode = "deleted"
	AckErrorCodeFutureEventTime    AckErrorCode = "future_event_time"
	AckErrorCodeUnsupportedVersion AckErrorCode = "unsupported_version"
	AckErrorCodeSchemaInvalid      AckErrorCode = "schema_invalid"
	AckErrorCodeHashMismatch       AckErrorCode = "hash_mismatch"
	AckErrorCodeNegativeCount      AckErrorCode = "negative_count"
	AckErrorCodeUnknownField       AckErrorCode = "unknown_field"
	AckErrorCodeDuplicateKey       AckErrorCode = "duplicate_key"
	AckErrorCodeDependencyExpired  AckErrorCode = "dependency_expired"
	AckErrorCodeInternalRetryable  AckErrorCode = "internal_retryable"
)

type ModelRef struct {
	ProviderID string `json:"providerId"`
	ModelID    string `json:"modelId"`
}

type SkillRef struct {
	SkillKey   Base64Url32 `json:"skillKey"`
	PublicName *string     `json:"publicName,omitempty"`
}

type UsagePayload struct {
	TokenTotal         *UInt64String `json:"token_total,omitempty"`
	InputContextTokens *UInt64String `json:"input_context_tokens,omitempty"`
	OutputTokens       *UInt64String `json:"output_tokens,omitempty"`
	CacheReadTokens    *UInt64String `json:"cache_read_tokens,omitempty"`
	CacheWriteTokens   *UInt64String `json:"cache_write_tokens,omitempty"`
	ReasoningTokens    *UInt64String `json:"reasoning_tokens,omitempty"`
	RequestCount       *UInt64String `json:"request_count,omitempty"`
}

type CostPayload struct {
	Units        UInt64String `json:"units"`
	Currency     string       `json:"currency"`
	Source       CostSource   `json:"source"`
	PriceBasisID *string      `json:"price_basis_id,omitempty"`
	Coverage     *string      `json:"coverage,omitempty"`
}

type CodePayload struct {
	Generated      *UInt64String `json:"generated,omitempty"`
	Accepted       *UInt64String `json:"accepted,omitempty"`
	Added          *UInt64String `json:"added,omitempty"`
	Removed        *UInt64String `json:"removed,omitempty"`
	FileTouchCount *UInt64String `json:"file_touch_count,omitempty"`
}

type ActivityPayload struct {
	DurationMs   *UInt64String     `json:"duration_ms,omitempty"`
	Success      *bool             `json:"success,omitempty"`
	Trigger      *TurnTrigger      `json:"trigger,omitempty"`
	Reason       *SessionEndReason `json:"reason,omitempty"`
	ToolCategory *string           `json:"tool_category,omitempty"`
}

type ContextPayload struct {
	ParentSessionKey *Base64Url32  `json:"parent_session_key,omitempty"`
	ToolCallKey      *Base64Url32  `json:"tool_call_key,omitempty"`
	ScopeStartedAt   *UInt64String `json:"scope_started_at,omitempty"`
	Coverage         *string       `json:"coverage,omitempty"`
}

type MetaPayload struct {
	Accuracy   Accuracy   `json:"accuracy"`
	TimeSource TimeSource `json:"time_source"`
	SafeTags   []string   `json:"safe_tags,omitempty"`
}

type EventPayload struct {
	Usage    *UsagePayload    `json:"usage,omitempty"`
	Cost     *CostPayload     `json:"cost,omitempty"`
	Code     *CodePayload     `json:"code,omitempty"`
	Activity *ActivityPayload `json:"activity,omitempty"`
	Context  *ContextPayload  `json:"context,omitempty"`
	Meta     *MetaPayload     `json:"meta,omitempty"`
}

type EventEnvelope struct {
	EventID                Base64Url32  `json:"eventId"`
	FactKey                Base64Url32  `json:"factKey"`
	FactRevision           UInt64String `json:"factRevision"`
	SchemaVersion          uint32       `json:"schemaVersion"`
	MetricSemanticsVersion uint32       `json:"metricSemanticsVersion"`
	HarnessID              string       `json:"harnessId"`
	EventType              EventType    `json:"eventType"`
	OccurredAt             UInt64String `json:"occurredAt"`
	Model                  *ModelRef    `json:"model,omitempty"`
	Skill                  *SkillRef    `json:"skill,omitempty"`
	SessionKey             *Base64Url32 `json:"sessionKey,omitempty"`
	TurnKey                *Base64Url32 `json:"turnKey,omitempty"`
	CostScopeKey           *Base64Url32 `json:"costScopeKey,omitempty"`
	Payload                EventPayload `json:"payload"`
	ContentHash            Base64Url32  `json:"contentHash"`
}

type TelemetryEventsRequest struct {
	ProtocolVersion uint32          `json:"protocolVersion"`
	RequestID       string          `json:"requestId"`
	Events          []EventEnvelope `json:"events"`
}

type EventAck struct {
	EventID     Base64Url32   `json:"eventId"`
	ContentHash Base64Url32   `json:"contentHash"`
	Result      AckResult     `json:"result"`
	Code        *AckErrorCode `json:"code,omitempty"`
}

type TelemetryEventsResponse struct {
	RequestID    string       `json:"requestId"`
	ServerTimeMs UInt64String `json:"serverTimeMs"`
	Acks         []EventAck   `json:"acks"`
}

type TelemetryCapabilities struct {
	ProtocolVersion                  uint32       `json:"protocolVersion"`
	SupportedSchemaVersions          []uint32     `json:"supportedSchemaVersions"`
	SupportedMetricSemanticsVersions []uint32     `json:"supportedMetricSemanticsVersions"`
	MaxBatchEvents                   uint32       `json:"maxBatchEvents"`
	MaxBatchBytes                    uint32       `json:"maxBatchBytes"`
	ServerTimeMs                     UInt64String `json:"serverTimeMs"`
	EventReceiveLowerBoundMs         UInt64String `json:"eventReceiveLowerBoundMs"`
}
