package domain

import "strings"

const legacyDesktopDeviceName = "TokenDance Desktop"

// IsGenericDeviceName identifies labels generated by older collectors or missing at registration.
func IsGenericDeviceName(name *string) bool {
	return name == nil || strings.TrimSpace(*name) == "" || strings.TrimSpace(*name) == legacyDesktopDeviceName
}

// IsAutoDeviceName also recognizes the per-installation fallback so a later
// collector with a real machine name can improve it without changing aliases.
func IsAutoDeviceName(name *string, osType, installationID string) bool {
	return IsGenericDeviceName(name) || *name == *InitialDeviceName(nil, osType, installationID)
}

// InitialDeviceName keeps a machine-provided label and gives older collectors a stable fallback.
// The suffix is derived from the already public installation ID, not a hardware fingerprint.
func InitialDeviceName(name *string, osType, installationID string) *string {
	if !IsGenericDeviceName(name) {
		trimmed := strings.TrimSpace(*name)
		return &trimmed
	}
	platform := "Device"
	switch osType {
	case "macos":
		platform = "Mac"
	case "windows":
		platform = "Windows"
	case "linux":
		platform = "Linux"
	}
	suffix := strings.TrimPrefix(installationID, "ins_")
	if len(suffix) > 6 {
		suffix = suffix[len(suffix)-6:]
	}
	if suffix == "" {
		suffix = "unknown"
	}
	fallback := platform + " · " + strings.ToUpper(suffix)
	return &fallback
}
