// Generated by tools/generate-protocol.mjs from schemas/protocol/v1/spec.json.
// Do not edit manually.

export const PROTOCOL_VERSION = "1.0" as const;
export type UInt64String = string;
export type DecimalString = string;
export type HmacSha256 = string;
export type Base64Url32 = string;

export const AdapterRuntimeStatusValues = ["UNDETECTED","DETECTED","NEEDS_PERMISSION","CONFIGURING","ACTIVE","DEGRADED","ERROR","DISABLED"] as const;
export type AdapterRuntimeStatus = (typeof AdapterRuntimeStatusValues)[number];

export const SetupPlanStatusValues = ["PROPOSED","APPROVED","APPLYING","VERIFYING","APPLIED","ROLLING_BACK","ROLLED_BACK","FAILED"] as const;
export type SetupPlanStatus = (typeof SetupPlanStatusValues)[number];

export const SourceCheckpointStatusValues = ["DISCOVERED","SCANNING","CURRENT","STALE","ROTATED","TRUNCATED","PERMISSION_DENIED","INCOMPATIBLE","ERROR","DISABLED"] as const;
export type SourceCheckpointStatus = (typeof SourceCheckpointStatusValues)[number];

export const EventDeliveryStatusValues = ["PENDING","QUEUED","IN_FLIGHT","ACKED","RETRYABLE","DEAD_LETTER"] as const;
export type EventDeliveryStatus = (typeof EventDeliveryStatusValues)[number];

export const ClientUploadBatchStatusValues = ["BUILDING","READY","IN_FLIGHT","ACKED","PARTIALLY_ACKED","RETRYABLE","FAILED"] as const;
export type ClientUploadBatchStatus = (typeof ClientUploadBatchStatusValues)[number];

export const AccuracyValues = ["exact","derived","correlated","estimated"] as const;
export type Accuracy = (typeof AccuracyValues)[number];

export const CapabilityAvailabilityValues = ["available","unavailable"] as const;
export type CapabilityAvailability = (typeof CapabilityAvailabilityValues)[number];

export const CapabilityValues = ["tokens","sessions","turns","tools","skills","code","cost","subagents"] as const;
export type Capability = (typeof CapabilityValues)[number];

export const SourceKindValues = ["otlp","jsonl_tail","sqlite_snapshot","file_snapshot","runtime_stream","local_http_api","command_snapshot","remote_api"] as const;
export type SourceKind = (typeof SourceKindValues)[number];

export const EventTypeValues = ["session_started","session_ended","turn_started","turn_completed","model_usage_recorded","tool_invoked","skill_invoked","code_changed","cost_recorded","agent_spawned"] as const;
export type EventType = (typeof EventTypeValues)[number];

export const CostSourceValues = ["provider_reported","estimated_price_table"] as const;
export type CostSource = (typeof CostSourceValues)[number];

export const SkillInvokeTypeValues = ["native","hook","tool_correlated","runtime_correlated"] as const;
export type SkillInvokeType = (typeof SkillInvokeTypeValues)[number];

export const SessionEndReasonValues = ["completed","cancelled","error","timeout","unknown"] as const;
export type SessionEndReason = (typeof SessionEndReasonValues)[number];

export const TurnTriggerValues = ["user","system","scheduled","subagent"] as const;
export type TurnTrigger = (typeof TurnTriggerValues)[number];

export const PlatformValues = ["windows-x64","windows-arm64","macos-x64","macos-arm64"] as const;
export type Platform = (typeof PlatformValues)[number];

export const OsTypeValues = ["windows","macos"] as const;
export type OsType = (typeof OsTypeValues)[number];

export const ArchitectureValues = ["x86_64","aarch64"] as const;
export type Architecture = (typeof ArchitectureValues)[number];

export const PathTemplateIdValues = ["USER_HOME","LOCAL_APP_DATA","ROAMING_APP_DATA","MAC_APP_SUPPORT","CODEX_HOME","AGENT_CONFIG_HOME"] as const;
export type PathTemplateId = (typeof PathTemplateIdValues)[number];

export const PathAccessValues = ["read","write"] as const;
export type PathAccess = (typeof PathAccessValues)[number];

export const RejectedEventErrorCodeValues = ["SCHEMA_INVALID","PRIVACY_REJECTED","EVENT_TOO_LARGE","UNSUPPORTED_VERSION","INTERNAL_RETRYABLE"] as const;
export type RejectedEventErrorCode = (typeof RejectedEventErrorCodeValues)[number];

export interface EventSource {
  kind: SourceKind
  cursorHmac: HmacSha256
  rawFingerprintHmac: HmacSha256
}

export interface TokenUsage {
  inputTokens?: UInt64String
  outputTokens?: UInt64String
  cacheReadTokens?: UInt64String
  cacheWriteTokens?: UInt64String
  reasoningTokens?: UInt64String
  toolTokens?: UInt64String
  totalTokens?: UInt64String
}

export interface SessionStartedPayload {
  type: "session_started"
  modelId?: string
  workspaceHash?: HmacSha256
}

export interface SessionEndedPayload {
  type: "session_ended"
  reason: SessionEndReason
  durationMs?: UInt64String
}

export interface TurnStartedPayload {
  type: "turn_started"
  trigger?: TurnTrigger
}

export interface TurnCompletedPayload {
  type: "turn_completed"
  success: boolean
  durationMs?: UInt64String
  errorClass?: string
}

export interface ModelUsageRecordedPayload {
  type: "model_usage_recorded"
  providerId: string
  modelId: string
  tokens: TokenUsage
}

export interface ToolInvokedPayload {
  type: "tool_invoked"
  toolCategory: string
  success: boolean
  durationMs?: UInt64String
}

export interface SkillInvokedPayload {
  type: "skill_invoked"
  skillKey: HmacSha256
  skillPublicName?: string
  invokeType: SkillInvokeType
  success: boolean
  pluginKey?: HmacSha256
  durationMs?: UInt64String
}

export interface CodeChangedPayload {
  type: "code_changed"
  addedLines: UInt64String
  removedLines: UInt64String
  generatedLines?: UInt64String
  acceptedLines?: UInt64String
  fileCount: number
  language?: string
}

export interface CostRecordedPayload {
  type: "cost_recorded"
  amount: DecimalString
  currency: string
  source: CostSource
  discountAmount?: DecimalString
}

export interface AgentSpawnedPayload {
  type: "agent_spawned"
  childSessionHash: HmacSha256
  spawnedAgentType: string
}

export interface EventEnvelope {
  schemaVersion: string
  eventId: Base64Url32
  adapterId: string
  adapterVersion: string
  agentId: string
  agentVersion?: string
  installationId: string
  occurredAt: string
  sessionHash?: HmacSha256
  turnHash?: HmacSha256
  toolCallHash?: HmacSha256
  source: EventSource
  accuracy: Accuracy
  payload: EventPayload
}

export interface AgentDescriptor {
  id: string
  versionRange: string
}

export interface PathPermission {
  template: PathTemplateId
  relativeGlob: string
  access: PathAccess
}

export interface CommandPermission {
  executableId: string
  args: Array<string>
}

export interface AdapterPermissions {
  readPaths: Array<PathPermission>
  writePaths: Array<PathPermission>
  commands: Array<CommandPermission>
  networkDomains: Array<string>
}

export interface AdapterManifest {
  $schema: string
  manifestVersion: string
  id: string
  name: string
  version: string
  protocolVersion: string
  agent: AgentDescriptor
  platforms: Array<Platform>
  sources: Array<SourceKind>
  permissions: AdapterPermissions
  capabilities: Array<Capability>
}

export interface UploadBatch {
  batchId: string
  installationId: string
  createdAt: string
  events: Array<EventEnvelope>
}

export interface RejectedEvent {
  eventId: Base64Url32
  errorCode: RejectedEventErrorCode
  retryable: boolean
}

export interface UploadAck {
  batchId: string
  accepted: number
  duplicates: number
  rejected: Array<RejectedEvent>
  serverTime: string
}

export interface UploadPolicy {
  maxBatchEvents: number
  maxBatchBytes: number
  flushIntervalSeconds: number
}

export interface InstallationRegisterRequest {
  devicePublicKey: Base64Url32
  osType: OsType
  architecture: Architecture
  collectorVersion: string
}

export interface InstallationRegisterResponse {
  installationId: string
  policy: UploadPolicy
}

export interface CapabilityStatus {
  capability: Capability
  availability: CapabilityAvailability
  accuracy?: Accuracy
  safeReasonCode?: string
}

export interface AdapterStatusReport {
  adapterId: string
  adapterVersion: string
  agentVersion?: string
  runtimeStatus: AdapterRuntimeStatus
  capabilities: Array<CapabilityStatus>
  sourceKinds: Array<SourceKind>
  safeErrorCode?: string
  reportedAt: string
}

export type EventPayload = SessionStartedPayload | SessionEndedPayload | TurnStartedPayload | TurnCompletedPayload | ModelUsageRecordedPayload | ToolInvokedPayload | SkillInvokedPayload | CodeChangedPayload | CostRecordedPayload | AgentSpawnedPayload

