// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AdapterRelease struct {
	AdapterID         string          `json:"adapter_id"`
	AdapterVersion    string          `json:"adapter_version"`
	OsType            string          `json:"os_type"`
	Architecture      string          `json:"architecture"`
	ArtifactUrl       string          `json:"artifact_url"`
	ArtifactSha256    []byte          `json:"artifact_sha256"`
	SignatureEd25519  []byte          `json:"signature_ed25519"`
	ManifestJson      json.RawMessage `json:"manifest_json"`
	CompatibilityJson json.RawMessage `json:"compatibility_json"`
	ReleaseStatus     string          `json:"release_status"`
	RolloutPercent    uint8           `json:"rollout_percent"`
	PublishedAt       sql.NullTime    `json:"published_at"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type DailySkillMetric struct {
	MetricDate         time.Time      `json:"metric_date"`
	UserID             string         `json:"user_id"`
	AgentID            string         `json:"agent_id"`
	SkillKey           []byte         `json:"skill_key"`
	SkillPublicName    sql.NullString `json:"skill_public_name"`
	UseCount           uint64         `json:"use_count"`
	ExactUseCount      uint64         `json:"exact_use_count"`
	DerivedUseCount    uint64         `json:"derived_use_count"`
	CorrelatedUseCount uint64         `json:"correlated_use_count"`
	EstimatedUseCount  uint64         `json:"estimated_use_count"`
	SuccessCount       uint64         `json:"success_count"`
	FailureCount       uint64         `json:"failure_count"`
	DurationMs         uint64         `json:"duration_ms"`
	SourceMaxEventPk   uint64         `json:"source_max_event_pk"`
	AggregationVersion uint32         `json:"aggregation_version"`
	ComputedAt         time.Time      `json:"computed_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type DailyUserAgentMetric struct {
	MetricDate           time.Time     `json:"metric_date"`
	UserID               string        `json:"user_id"`
	AgentID              string        `json:"agent_id"`
	ExactTokenTotal      uint64        `json:"exact_token_total"`
	DerivedTokenTotal    uint64        `json:"derived_token_total"`
	EstimatedTokenTotal  uint64        `json:"estimated_token_total"`
	SessionCount         uint64        `json:"session_count"`
	ChildSessionCount    uint64        `json:"child_session_count"`
	InteractionTurnCount uint64        `json:"interaction_turn_count"`
	ModelRequestCount    uint64        `json:"model_request_count"`
	ToolCallCount        uint64        `json:"tool_call_count"`
	SkillUseCount        uint64        `json:"skill_use_count"`
	CodeGeneratedLines   uint64        `json:"code_generated_lines"`
	CodeAcceptedLines    uint64        `json:"code_accepted_lines"`
	CorrelatedCodeLines  uint64        `json:"correlated_code_lines"`
	CostAmount           string        `json:"cost_amount"`
	CostCurrency         string        `json:"cost_currency"`
	SourceMaxEventPk     uint64        `json:"source_max_event_pk"`
	AggregationVersion   uint32        `json:"aggregation_version"`
	ComputedAt           time.Time     `json:"computed_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	TokenInputTotal      sql.NullInt64 `json:"token_input_total"`
	TokenOutputTotal     sql.NullInt64 `json:"token_output_total"`
	TokenCacheReadTotal  sql.NullInt64 `json:"token_cache_read_total"`
	TokenCacheWriteTotal sql.NullInt64 `json:"token_cache_write_total"`
	TokenReasoningTotal  sql.NullInt64 `json:"token_reasoning_total"`
	ActiveDurationMs     sql.NullInt64 `json:"active_duration_ms"`
	MessageCount         sql.NullInt64 `json:"message_count"`
	UserMessageCount     sql.NullInt64 `json:"user_message_count"`
}

type DailyUserAgentModelMetric struct {
	MetricDate           time.Time     `json:"metric_date"`
	UserID               string        `json:"user_id"`
	AgentID              string        `json:"agent_id"`
	ProviderID           string        `json:"provider_id"`
	ModelID              string        `json:"model_id"`
	ExactTokenTotal      uint64        `json:"exact_token_total"`
	DerivedTokenTotal    uint64        `json:"derived_token_total"`
	EstimatedTokenTotal  uint64        `json:"estimated_token_total"`
	ModelRequestCount    uint64        `json:"model_request_count"`
	CostAmount           string        `json:"cost_amount"`
	CostCurrency         string        `json:"cost_currency"`
	SourceMaxEventPk     uint64        `json:"source_max_event_pk"`
	AggregationVersion   uint32        `json:"aggregation_version"`
	ComputedAt           time.Time     `json:"computed_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	TokenInputTotal      sql.NullInt64 `json:"token_input_total"`
	TokenOutputTotal     sql.NullInt64 `json:"token_output_total"`
	TokenCacheReadTotal  sql.NullInt64 `json:"token_cache_read_total"`
	TokenCacheWriteTotal sql.NullInt64 `json:"token_cache_write_total"`
	TokenReasoningTotal  sql.NullInt64 `json:"token_reasoning_total"`
}

type DataDeletionRequest struct {
	RequestID        string          `json:"request_id"`
	UserID           sql.NullString  `json:"user_id"`
	InstallationID   sql.NullString  `json:"installation_id"`
	DeletionScope    string          `json:"deletion_scope"`
	RequestStatus    string          `json:"request_status"`
	RequestedAt      time.Time       `json:"requested_at"`
	StartedAt        sql.NullTime    `json:"started_at"`
	CompletedAt      sql.NullTime    `json:"completed_at"`
	ErrorCode        sql.NullString  `json:"error_code"`
	AuditReference   sql.NullString  `json:"audit_reference"`
	CancelBefore     sql.NullTime    `json:"cancel_before"`
	CancelledAt      sql.NullTime    `json:"cancelled_at"`
	ScopeFilterJson  json.RawMessage `json:"scope_filter_json"`
	Phase            string          `json:"phase"`
	ProgressCursor   uint64          `json:"progress_cursor"`
	ActiveAccountKey sql.NullString  `json:"active_account_key"`
	ClaimToken       sql.NullString  `json:"claim_token"`
	ClaimGeneration  uint64          `json:"claim_generation"`
	LockedBy         sql.NullString  `json:"locked_by"`
	LeaseExpiresAt   sql.NullTime    `json:"lease_expires_at"`
	AttemptCount     uint16          `json:"attempt_count"`
	NextAttemptAt    time.Time       `json:"next_attempt_at"`
	LastErrorCode    sql.NullString  `json:"last_error_code"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type DataExportJob struct {
	ExportID       string          `json:"export_id"`
	UserID         string          `json:"user_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	RequestHash    []byte          `json:"request_hash"`
	ExportScope    string          `json:"export_scope"`
	ExportFormat   string          `json:"export_format"`
	FilterJson     json.RawMessage `json:"filter_json"`
	JobStatus      string          `json:"job_status"`
	AttemptCount   uint16          `json:"attempt_count"`
	NextAttemptAt  time.Time       `json:"next_attempt_at"`
	LockedAt       sql.NullTime    `json:"locked_at"`
	LockedBy       sql.NullString  `json:"locked_by"`
	ObjectKey      sql.NullString  `json:"object_key"`
	FileSha256     sql.NullString  `json:"file_sha256"`
	FileSize       sql.NullInt64   `json:"file_size"`
	LastErrorCode  sql.NullString  `json:"last_error_code"`
	StartedAt      sql.NullTime    `json:"started_at"`
	CompletedAt    sql.NullTime    `json:"completed_at"`
	ExpiresAt      sql.NullTime    `json:"expires_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type DeletionObjectKey struct {
	RequestID      string         `json:"request_id"`
	ObjectKey      string         `json:"object_key"`
	ObjectKind     string         `json:"object_kind"`
	DeletionStatus string         `json:"deletion_status"`
	AttemptCount   uint16         `json:"attempt_count"`
	LastErrorCode  sql.NullString `json:"last_error_code"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type DeviceBindingChallenge struct {
	ChallengeID            string         `json:"challenge_id"`
	UserID                 string         `json:"user_id"`
	SessionID              string         `json:"session_id"`
	CodeLookupHash         []byte         `json:"code_lookup_hash"`
	CodeKeyVersion         uint16         `json:"code_key_version"`
	ChallengeStatus        string         `json:"challenge_status"`
	ExpiresAt              time.Time      `json:"expires_at"`
	ConsumedInstallationID sql.NullString `json:"consumed_installation_id"`
	ConsumedAt             sql.NullTime   `json:"consumed_at"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	ActiveSessionKey       sql.NullString `json:"active_session_key"`
}

type EmailChallenge struct {
	ChallengeID           string         `json:"challenge_id"`
	UserID                sql.NullString `json:"user_id"`
	EmailLookupHash       []byte         `json:"email_lookup_hash"`
	EmailCiphertext       []byte         `json:"email_ciphertext"`
	EmailKeyVersion       uint16         `json:"email_key_version"`
	ChallengeType         string         `json:"challenge_type"`
	CodeHash              []byte         `json:"code_hash"`
	CodeKeyVersion        uint16         `json:"code_key_version"`
	ChallengeStatus       string         `json:"challenge_status"`
	AttemptCount          uint16         `json:"attempt_count"`
	MaxAttempts           uint16         `json:"max_attempts"`
	SendCount             uint16         `json:"send_count"`
	RequestedIpPrefixHash sql.NullString `json:"requested_ip_prefix_hash"`
	ExpiresAt             time.Time      `json:"expires_at"`
	ConsumedAt            sql.NullTime   `json:"consumed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ActiveEmailLookupHash sql.NullString `json:"active_email_lookup_hash"`
}

type EmailOutbox struct {
	EmailID              string         `json:"email_id"`
	UserID               sql.NullString `json:"user_id"`
	ChallengeID          sql.NullString `json:"challenge_id"`
	IdempotencyKey       []byte         `json:"idempotency_key"`
	TemplateKey          string         `json:"template_key"`
	Locale               string         `json:"locale"`
	RecipientCiphertext  []byte         `json:"recipient_ciphertext"`
	PayloadCiphertext    []byte         `json:"payload_ciphertext"`
	EncryptionKeyVersion uint16         `json:"encryption_key_version"`
	DeliveryStatus       string         `json:"delivery_status"`
	AttemptCount         uint16         `json:"attempt_count"`
	NextAttemptAt        time.Time      `json:"next_attempt_at"`
	LockedAt             sql.NullTime   `json:"locked_at"`
	LockedBy             sql.NullString `json:"locked_by"`
	ProviderMessageID    sql.NullString `json:"provider_message_id"`
	LastErrorCode        sql.NullString `json:"last_error_code"`
	SentAt               sql.NullTime   `json:"sent_at"`
	ExpiresAt            time.Time      `json:"expires_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type IngestBatch struct {
	BatchID        string         `json:"batch_id"`
	InstallationID string         `json:"installation_id"`
	RequestSha256  []byte         `json:"request_sha256"`
	EventCount     uint32         `json:"event_count"`
	AcceptedCount  uint32         `json:"accepted_count"`
	DuplicateCount uint32         `json:"duplicate_count"`
	RejectedCount  uint32         `json:"rejected_count"`
	BatchStatus    string         `json:"batch_status"`
	LastErrorCode  sql.NullString `json:"last_error_code"`
	ReceivedAt     time.Time      `json:"received_at"`
	CommittedAt    sql.NullTime   `json:"committed_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type IngestNonce struct {
	InstallationID string    `json:"installation_id"`
	NonceHash      []byte    `json:"nonce_hash"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type Installation struct {
	InstallationID     string         `json:"installation_id"`
	UserID             string         `json:"user_id"`
	DevicePublicKey    []byte         `json:"device_public_key"`
	DeviceName         sql.NullString `json:"device_name"`
	OsType             string         `json:"os_type"`
	OsVersion          sql.NullString `json:"os_version"`
	Architecture       string         `json:"architecture"`
	CollectorVersion   string         `json:"collector_version"`
	InstallationStatus string         `json:"installation_status"`
	RegisteredAt       time.Time      `json:"registered_at"`
	LastSeenAt         sql.NullTime   `json:"last_seen_at"`
	RevokedAt          sql.NullTime   `json:"revoked_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DisabledAt         sql.NullTime   `json:"disabled_at"`
	DisabledReason     sql.NullString `json:"disabled_reason"`
	StatusVersion      uint64         `json:"status_version"`
}

type InstallationAdapterStatus struct {
	InstallationID string          `json:"installation_id"`
	AdapterID      string          `json:"adapter_id"`
	AdapterVersion string          `json:"adapter_version"`
	AgentVersion   sql.NullString  `json:"agent_version"`
	RuntimeStatus  string          `json:"runtime_status"`
	CapabilityJson json.RawMessage `json:"capability_json"`
	SafeErrorCode  sql.NullString  `json:"safe_error_code"`
	LastProbeAt    sql.NullTime    `json:"last_probe_at"`
	LastEventAt    sql.NullTime    `json:"last_event_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type LeaderboardEntry struct {
	SnapshotID          string          `json:"snapshot_id"`
	RankNo              uint32          `json:"rank_no"`
	UserID              string          `json:"user_id"`
	MetricValue         string          `json:"metric_value"`
	PreviousRankNo      sql.NullInt32   `json:"previous_rank_no"`
	DisplayNameSnapshot string          `json:"display_name_snapshot"`
	AvatarUrlSnapshot   sql.NullString  `json:"avatar_url_snapshot"`
	BreakdownJson       json.RawMessage `json:"breakdown_json"`
}

type LeaderboardSnapshot struct {
	SnapshotID         string       `json:"snapshot_id"`
	BoardKey           string       `json:"board_key"`
	ScopeType          string       `json:"scope_type"`
	ScopeKey           string       `json:"scope_key"`
	MetricKey          string       `json:"metric_key"`
	WindowStart        time.Time    `json:"window_start"`
	WindowEnd          time.Time    `json:"window_end"`
	TimezoneName       string       `json:"timezone_name"`
	RankingRuleVersion uint32       `json:"ranking_rule_version"`
	ParticipantCount   uint32       `json:"participant_count"`
	SourceMaxEventPk   uint64       `json:"source_max_event_pk"`
	DataWatermarkAt    time.Time    `json:"data_watermark_at"`
	SnapshotStatus     string       `json:"snapshot_status"`
	GeneratedAt        time.Time    `json:"generated_at"`
	PublishedAt        sql.NullTime `json:"published_at"`
}

type PublicUserProfile struct {
	UserID               string         `json:"user_id"`
	Handle               string         `json:"handle"`
	DisplayName          string         `json:"display_name"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	Bio                  sql.NullString `json:"bio"`
	ProfileStatus        string         `json:"profile_status"`
	ShowBio              bool           `json:"show_bio"`
	ShowTokenTotal       bool           `json:"show_token_total"`
	ShowTrends           bool           `json:"show_trends"`
	ShowActivityCalendar bool           `json:"show_activity_calendar"`
	ShowAgentBreakdown   bool           `json:"show_agent_breakdown"`
	ShowSkillRanking     bool           `json:"show_skill_ranking"`
	ShowAchievements     bool           `json:"show_achievements"`
	SourceProfileVersion uint64         `json:"source_profile_version"`
	SourcePrivacyVersion uint64         `json:"source_privacy_version"`
	ProjectionVersion    uint64         `json:"projection_version"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type SchemaMigration struct {
	Version        string       `json:"version"`
	ChecksumSha256 []byte       `json:"checksum_sha256"`
	Dirty          bool         `json:"dirty"`
	StatementCount uint32       `json:"statement_count"`
	LastStatement  uint32       `json:"last_statement"`
	AppliedAt      sql.NullTime `json:"applied_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type UsageEvent struct {
	EventPk              uint64          `json:"event_pk"`
	EventID              []byte          `json:"event_id"`
	SchemaVersion        uint16          `json:"schema_version"`
	BatchID              string          `json:"batch_id"`
	InstallationID       string          `json:"installation_id"`
	UserID               string          `json:"user_id"`
	AdapterID            string          `json:"adapter_id"`
	AdapterVersion       string          `json:"adapter_version"`
	AgentID              string          `json:"agent_id"`
	AgentVersion         sql.NullString  `json:"agent_version"`
	ProviderID           sql.NullString  `json:"provider_id"`
	ModelID              sql.NullString  `json:"model_id"`
	EventType            string          `json:"event_type"`
	Accuracy             string          `json:"accuracy"`
	SourceKind           string          `json:"source_kind"`
	OccurredAt           time.Time       `json:"occurred_at"`
	OccurredDate         sql.NullTime    `json:"occurred_date"`
	ReceivedAt           time.Time       `json:"received_at"`
	SessionHash          sql.NullString  `json:"session_hash"`
	ParentSessionHash    sql.NullString  `json:"parent_session_hash"`
	TurnHash             sql.NullString  `json:"turn_hash"`
	ToolCallHash         sql.NullString  `json:"tool_call_hash"`
	TokenInput           sql.NullInt64   `json:"token_input"`
	TokenOutput          sql.NullInt64   `json:"token_output"`
	TokenCacheRead       sql.NullInt64   `json:"token_cache_read"`
	TokenCacheWrite      sql.NullInt64   `json:"token_cache_write"`
	TokenReasoning       sql.NullInt64   `json:"token_reasoning"`
	TokenTotal           sql.NullInt64   `json:"token_total"`
	DurationMs           sql.NullInt64   `json:"duration_ms"`
	Success              sql.NullBool    `json:"success"`
	ToolCategory         sql.NullString  `json:"tool_category"`
	SkillKey             sql.NullString  `json:"skill_key"`
	SkillPublicName      sql.NullString  `json:"skill_public_name"`
	SkillInvokeType      sql.NullString  `json:"skill_invoke_type"`
	PluginKey            sql.NullString  `json:"plugin_key"`
	CodeGeneratedLines   sql.NullInt64   `json:"code_generated_lines"`
	CodeAcceptedLines    sql.NullInt64   `json:"code_accepted_lines"`
	CodeAddedLines       sql.NullInt64   `json:"code_added_lines"`
	CodeDeletedLines     sql.NullInt64   `json:"code_deleted_lines"`
	CodeFileCount        sql.NullInt32   `json:"code_file_count"`
	CostAmount           sql.NullString  `json:"cost_amount"`
	CostCurrency         sql.NullString  `json:"cost_currency"`
	CostSource           sql.NullString  `json:"cost_source"`
	PrivacyPolicyVersion uint16          `json:"privacy_policy_version"`
	SafeExtensionJson    json.RawMessage `json:"safe_extension_json"`
	CreatedAt            time.Time       `json:"created_at"`
	TurnTrigger          sql.NullString  `json:"turn_trigger"`
}

type User struct {
	UserID                 string         `json:"user_id"`
	AuthSubjectHash        []byte         `json:"auth_subject_hash"`
	EmailLookupHash        sql.NullString `json:"email_lookup_hash"`
	EmailCiphertext        sql.NullString `json:"email_ciphertext"`
	DisplayName            string         `json:"display_name"`
	AvatarUrl              sql.NullString `json:"avatar_url"`
	AccountStatus          string         `json:"account_status"`
	LeaderboardVisibility  string         `json:"leaderboard_visibility"`
	TimezoneName           string         `json:"timezone_name"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	Handle                 sql.NullString `json:"handle"`
	EmailVerifiedAt        sql.NullTime   `json:"email_verified_at"`
	AvatarObjectID         sql.NullString `json:"avatar_object_id"`
	Bio                    sql.NullString `json:"bio"`
	Locale                 string         `json:"locale"`
	OnboardingCompletedAt  sql.NullTime   `json:"onboarding_completed_at"`
	ProfileVersion         uint64         `json:"profile_version"`
	PublicProfileUpdatedAt sql.NullTime   `json:"public_profile_updated_at"`
}

type UserHandleHistory struct {
	Handle        string    `json:"handle"`
	UserID        string    `json:"user_id"`
	RedirectUntil time.Time `json:"redirect_until"`
	ReservedUntil time.Time `json:"reserved_until"`
	CreatedAt     time.Time `json:"created_at"`
}

type UserPasswordCredential struct {
	UserID            string       `json:"user_id"`
	PasswordHash      string       `json:"password_hash"`
	PasswordAlgorithm string       `json:"password_algorithm"`
	CredentialVersion uint32       `json:"credential_version"`
	FailedLoginCount  uint16       `json:"failed_login_count"`
	LockedUntil       sql.NullTime `json:"locked_until"`
	LastFailedLoginAt sql.NullTime `json:"last_failed_login_at"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}

type UserPrivacySetting struct {
	UserID               string    `json:"user_id"`
	PublicProfileEnabled bool      `json:"public_profile_enabled"`
	ShowBio              bool      `json:"show_bio"`
	ShowTokenTotal       bool      `json:"show_token_total"`
	ShowTrends           bool      `json:"show_trends"`
	ShowActivityCalendar bool      `json:"show_activity_calendar"`
	ShowAgentBreakdown   bool      `json:"show_agent_breakdown"`
	ShowSkillRanking     bool      `json:"show_skill_ranking"`
	ShowAchievements     bool      `json:"show_achievements"`
	PrivacyVersion       uint64    `json:"privacy_version"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type UserSecurityEvent struct {
	EventID           string          `json:"event_id"`
	UserID            sql.NullString  `json:"user_id"`
	SessionID         sql.NullString  `json:"session_id"`
	EventType         string          `json:"event_type"`
	Outcome           string          `json:"outcome"`
	SubjectLookupHash sql.NullString  `json:"subject_lookup_hash"`
	IpPrefixHash      sql.NullString  `json:"ip_prefix_hash"`
	UserAgentHash     sql.NullString  `json:"user_agent_hash"`
	MetadataJson      json.RawMessage `json:"metadata_json"`
	CreatedAt         time.Time       `json:"created_at"`
}

type UserSession struct {
	SessionID         string         `json:"session_id"`
	UserID            string         `json:"user_id"`
	SessionTokenHash  []byte         `json:"session_token_hash"`
	CsrfTokenHash     []byte         `json:"csrf_token_hash"`
	CredentialVersion uint32         `json:"credential_version"`
	SessionStatus     string         `json:"session_status"`
	DeviceLabel       sql.NullString `json:"device_label"`
	UserAgentHash     sql.NullString `json:"user_agent_hash"`
	IpPrefixHash      sql.NullString `json:"ip_prefix_hash"`
	LastSeenAt        time.Time      `json:"last_seen_at"`
	IdleExpiresAt     time.Time      `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time      `json:"absolute_expires_at"`
	RevokedAt         sql.NullTime   `json:"revoked_at"`
	RevokeReason      sql.NullString `json:"revoke_reason"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type UserUploadObject struct {
	ObjectID      string         `json:"object_id"`
	UserID        string         `json:"user_id"`
	ObjectType    string         `json:"object_type"`
	ObjectKey     string         `json:"object_key"`
	ContentType   sql.NullString `json:"content_type"`
	ByteSize      sql.NullInt64  `json:"byte_size"`
	ContentSha256 sql.NullString `json:"content_sha256"`
	ImageWidth    sql.NullInt32  `json:"image_width"`
	ImageHeight   sql.NullInt32  `json:"image_height"`
	UploadStatus  string         `json:"upload_status"`
	ExpiresAt     time.Time      `json:"expires_at"`
	LastErrorCode sql.NullString `json:"last_error_code"`
	UploadedAt    sql.NullTime   `json:"uploaded_at"`
	ReadyAt       sql.NullTime   `json:"ready_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
