// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const searchPublicSkills = `-- name: SearchPublicSkills :many
SELECT
    HEX(s.skill_key) AS skill_hex,
    s.skill_public_name,
    SUM(s.use_count) AS total_use_count,
    COUNT(DISTINCT s.user_id) AS public_user_count,
    COUNT(DISTINCT s.metric_date) AS active_days
FROM daily_skill_metrics s
JOIN users u ON s.user_id = u.user_id
JOIN public_user_profiles p ON s.user_id = p.user_id
JOIN user_privacy_settings priv ON s.user_id = priv.user_id
WHERE u.account_status = 'active'
  AND u.leaderboard_visibility = 'public'
  AND p.profile_status = 'published'
  AND priv.public_profile_enabled = TRUE
  AND priv.show_skill_ranking = TRUE
  AND s.skill_public_name IS NOT NULL
  AND s.skill_public_name != ''
  AND (LOWER(s.skill_public_name) LIKE ? OR LOWER(HEX(s.skill_key)) LIKE ?)
GROUP BY s.skill_key, s.skill_public_name
HAVING public_user_count >= 5 AND active_days >= 3
ORDER BY total_use_count DESC
LIMIT ?
`

type SearchPublicSkillsParams struct {
	NamePattern sql.NullString `json:"name_pattern"`
	KeyPattern  []byte         `json:"key_pattern"`
	Limit       int32          `json:"limit"`
}

type SearchPublicSkillsRow struct {
	SkillHex        string         `json:"skill_hex"`
	SkillPublicName sql.NullString `json:"skill_public_name"`
	TotalUseCount   interface{}    `json:"total_use_count"`
	PublicUserCount int64          `json:"public_user_count"`
	ActiveDays      int64          `json:"active_days"`
}

func (q *Queries) SearchPublicSkills(ctx context.Context, arg SearchPublicSkillsParams) ([]SearchPublicSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPublicSkills, arg.NamePattern, arg.KeyPattern, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPublicSkillsRow{}
	for rows.Next() {
		var i SearchPublicSkillsRow
		if err := rows.Scan(
			&i.SkillHex,
			&i.SkillPublicName,
			&i.TotalUseCount,
			&i.PublicUserCount,
			&i.ActiveDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicUsers = `-- name: SearchPublicUsers :many
SELECT p.handle, p.display_name, p.avatar_url, p.bio
FROM public_user_profiles p
JOIN users u ON p.user_id = u.user_id
JOIN user_privacy_settings priv ON p.user_id = priv.user_id
WHERE p.profile_status = 'published'
  AND u.account_status = 'active'
  AND u.leaderboard_visibility = 'public'
  AND priv.public_profile_enabled = TRUE
  AND (LOWER(p.handle) LIKE ? OR LOWER(p.display_name) LIKE ?)
ORDER BY (LOWER(p.handle) = LOWER(?)) DESC, p.handle ASC
LIMIT ?
`

type SearchPublicUsersParams struct {
	SearchPattern string `json:"search_pattern"`
	ExactHandle   string `json:"exact_handle"`
	Limit         int32  `json:"limit"`
}

type SearchPublicUsersRow struct {
	Handle      string         `json:"handle"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
}

func (q *Queries) SearchPublicUsers(ctx context.Context, arg SearchPublicUsersParams) ([]SearchPublicUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPublicUsers,
		arg.SearchPattern,
		arg.SearchPattern,
		arg.ExactHandle,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPublicUsersRow{}
	for rows.Next() {
		var i SearchPublicUsersRow
		if err := rows.Scan(
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
