// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: static_store.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const cancelBindingChallengeByOwner = `-- name: CancelBindingChallengeByOwner :execrows
UPDATE device_binding_challenges
SET challenge_status = 'cancelled', active_session_key = NULL, updated_at = ?
WHERE challenge_id = ? AND user_id = ?
`

type CancelBindingChallengeByOwnerParams struct {
	UpdatedAt   time.Time `json:"updated_at"`
	ChallengeID string    `json:"challenge_id"`
	UserID      string    `json:"user_id"`
}

func (q *Queries) CancelBindingChallengeByOwner(ctx context.Context, arg CancelBindingChallengeByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelBindingChallengeByOwner, arg.UpdatedAt, arg.ChallengeID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeExportJob = `-- name: CompleteExportJob :execrows
UPDATE data_export_jobs
SET job_status = 'completed', object_key = ?, file_sha256 = ?, file_size = ?,
    completed_at = ?, expires_at = ?, locked_at = NULL, locked_by = NULL, updated_at = ?
WHERE export_id = ? AND (locked_by = ? OR locked_by IS NULL)
`

type CompleteExportJobParams struct {
	ObjectKey   sql.NullString `json:"object_key"`
	FileSha256  sql.NullString `json:"file_sha256"`
	FileSize    sql.NullInt64  `json:"file_size"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ExportID    string         `json:"export_id"`
	LockedBy    sql.NullString `json:"locked_by"`
}

func (q *Queries) CompleteExportJob(ctx context.Context, arg CompleteExportJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExportJob,
		arg.ObjectKey,
		arg.FileSha256,
		arg.FileSize,
		arg.CompletedAt,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ExportID,
		arg.LockedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createUploadObject = `-- name: CreateUploadObject :exec
INSERT INTO user_upload_objects (
    object_id, user_id, object_type, object_key, content_type, byte_size,
    content_sha256, upload_status, expires_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUploadObjectParams struct {
	ObjectID      string         `json:"object_id"`
	UserID        string         `json:"user_id"`
	ObjectType    string         `json:"object_type"`
	ObjectKey     string         `json:"object_key"`
	ContentType   sql.NullString `json:"content_type"`
	ByteSize      sql.NullInt64  `json:"byte_size"`
	ContentSha256 sql.NullString `json:"content_sha256"`
	UploadStatus  string         `json:"upload_status"`
	ExpiresAt     time.Time      `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUploadObject(ctx context.Context, arg CreateUploadObjectParams) error {
	_, err := q.db.ExecContext(ctx, createUploadObject,
		arg.ObjectID,
		arg.UserID,
		arg.ObjectType,
		arg.ObjectKey,
		arg.ContentType,
		arg.ByteSize,
		arg.ContentSha256,
		arg.UploadStatus,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSnapshotEntries = `-- name: DeleteSnapshotEntries :exec
DELETE FROM leaderboard_entries
WHERE snapshot_id = ?
`

func (q *Queries) DeleteSnapshotEntries(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotEntries, snapshotID)
	return err
}

const getDeletionRequestByOwner = `-- name: GetDeletionRequestByOwner :one
SELECT request_id, user_id, deletion_scope, scope_filter_json, request_status, phase,
       progress_cursor, cancel_before, cancelled_at, requested_at, completed_at, audit_reference
FROM data_deletion_requests
WHERE request_id = ? AND user_id = ?
LIMIT 1
`

type GetDeletionRequestByOwnerParams struct {
	RequestID string         `json:"request_id"`
	UserID    sql.NullString `json:"user_id"`
}

type GetDeletionRequestByOwnerRow struct {
	RequestID       string          `json:"request_id"`
	UserID          sql.NullString  `json:"user_id"`
	DeletionScope   string          `json:"deletion_scope"`
	ScopeFilterJson json.RawMessage `json:"scope_filter_json"`
	RequestStatus   string          `json:"request_status"`
	Phase           string          `json:"phase"`
	ProgressCursor  uint64          `json:"progress_cursor"`
	CancelBefore    sql.NullTime    `json:"cancel_before"`
	CancelledAt     sql.NullTime    `json:"cancelled_at"`
	RequestedAt     time.Time       `json:"requested_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	AuditReference  sql.NullString  `json:"audit_reference"`
}

func (q *Queries) GetDeletionRequestByOwner(ctx context.Context, arg GetDeletionRequestByOwnerParams) (GetDeletionRequestByOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getDeletionRequestByOwner, arg.RequestID, arg.UserID)
	var i GetDeletionRequestByOwnerRow
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.DeletionScope,
		&i.ScopeFilterJson,
		&i.RequestStatus,
		&i.Phase,
		&i.ProgressCursor,
		&i.CancelBefore,
		&i.CancelledAt,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.AuditReference,
	)
	return i, err
}

const getExportJobByOwner = `-- name: GetExportJobByOwner :one
SELECT export_id, user_id, idempotency_key, request_hash, export_scope, export_format,
       filter_json, job_status, attempt_count, next_attempt_at, locked_at, locked_by,
       object_key, file_sha256, file_size, last_error_code, started_at, completed_at,
       expires_at, created_at, updated_at
FROM data_export_jobs
WHERE export_id = ? AND user_id = ?
LIMIT 1
`

type GetExportJobByOwnerParams struct {
	ExportID string `json:"export_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetExportJobByOwner(ctx context.Context, arg GetExportJobByOwnerParams) (DataExportJob, error) {
	row := q.db.QueryRowContext(ctx, getExportJobByOwner, arg.ExportID, arg.UserID)
	var i DataExportJob
	err := row.Scan(
		&i.ExportID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ExportScope,
		&i.ExportFormat,
		&i.FilterJson,
		&i.JobStatus,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.ObjectKey,
		&i.FileSha256,
		&i.FileSize,
		&i.LastErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngestInstallationByID = `-- name: GetIngestInstallationByID :one
SELECT installation_id, user_id, device_public_key, device_name, os_type, os_version,
       architecture, collector_version, installation_status, disabled_at, disabled_reason,
       status_version, registered_at, last_seen_at, revoked_at, updated_at
FROM installations
WHERE installation_id = ?
`

type GetIngestInstallationByIDRow struct {
	InstallationID     string         `json:"installation_id"`
	UserID             string         `json:"user_id"`
	DevicePublicKey    []byte         `json:"device_public_key"`
	DeviceName         sql.NullString `json:"device_name"`
	OsType             string         `json:"os_type"`
	OsVersion          sql.NullString `json:"os_version"`
	Architecture       string         `json:"architecture"`
	CollectorVersion   string         `json:"collector_version"`
	InstallationStatus string         `json:"installation_status"`
	DisabledAt         sql.NullTime   `json:"disabled_at"`
	DisabledReason     sql.NullString `json:"disabled_reason"`
	StatusVersion      uint64         `json:"status_version"`
	RegisteredAt       time.Time      `json:"registered_at"`
	LastSeenAt         sql.NullTime   `json:"last_seen_at"`
	RevokedAt          sql.NullTime   `json:"revoked_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

func (q *Queries) GetIngestInstallationByID(ctx context.Context, installationID string) (GetIngestInstallationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIngestInstallationByID, installationID)
	var i GetIngestInstallationByIDRow
	err := row.Scan(
		&i.InstallationID,
		&i.UserID,
		&i.DevicePublicKey,
		&i.DeviceName,
		&i.OsType,
		&i.OsVersion,
		&i.Architecture,
		&i.CollectorVersion,
		&i.InstallationStatus,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.StatusVersion,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByOwner = `-- name: GetInstallationByOwner :one
SELECT installation_id, user_id, device_public_key, device_name, os_type, os_version,
       architecture, collector_version, installation_status, disabled_at, disabled_reason,
       status_version, registered_at, last_seen_at, revoked_at, updated_at
FROM installations
WHERE installation_id = ? AND user_id = ?
LIMIT 1
`

type GetInstallationByOwnerParams struct {
	InstallationID string `json:"installation_id"`
	UserID         string `json:"user_id"`
}

type GetInstallationByOwnerRow struct {
	InstallationID     string         `json:"installation_id"`
	UserID             string         `json:"user_id"`
	DevicePublicKey    []byte         `json:"device_public_key"`
	DeviceName         sql.NullString `json:"device_name"`
	OsType             string         `json:"os_type"`
	OsVersion          sql.NullString `json:"os_version"`
	Architecture       string         `json:"architecture"`
	CollectorVersion   string         `json:"collector_version"`
	InstallationStatus string         `json:"installation_status"`
	DisabledAt         sql.NullTime   `json:"disabled_at"`
	DisabledReason     sql.NullString `json:"disabled_reason"`
	StatusVersion      uint64         `json:"status_version"`
	RegisteredAt       time.Time      `json:"registered_at"`
	LastSeenAt         sql.NullTime   `json:"last_seen_at"`
	RevokedAt          sql.NullTime   `json:"revoked_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

func (q *Queries) GetInstallationByOwner(ctx context.Context, arg GetInstallationByOwnerParams) (GetInstallationByOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getInstallationByOwner, arg.InstallationID, arg.UserID)
	var i GetInstallationByOwnerRow
	err := row.Scan(
		&i.InstallationID,
		&i.UserID,
		&i.DevicePublicKey,
		&i.DeviceName,
		&i.OsType,
		&i.OsVersion,
		&i.Architecture,
		&i.CollectorVersion,
		&i.InstallationStatus,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.StatusVersion,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPublishedSnapshot = `-- name: GetLatestPublishedSnapshot :one
SELECT snapshot_id, data_watermark_at
FROM leaderboard_snapshots
WHERE board_key = ? AND metric_key = ? AND snapshot_status = 'published'
ORDER BY published_at DESC
LIMIT 1
`

type GetLatestPublishedSnapshotParams struct {
	BoardKey  string `json:"board_key"`
	MetricKey string `json:"metric_key"`
}

type GetLatestPublishedSnapshotRow struct {
	SnapshotID      string    `json:"snapshot_id"`
	DataWatermarkAt time.Time `json:"data_watermark_at"`
}

func (q *Queries) GetLatestPublishedSnapshot(ctx context.Context, arg GetLatestPublishedSnapshotParams) (GetLatestPublishedSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedSnapshot, arg.BoardKey, arg.MetricKey)
	var i GetLatestPublishedSnapshotRow
	err := row.Scan(&i.SnapshotID, &i.DataWatermarkAt)
	return i, err
}

const getLatestPublishedSnapshotByBoard = `-- name: GetLatestPublishedSnapshotByBoard :one
SELECT snapshot_id, data_watermark_at
FROM leaderboard_snapshots
WHERE board_key = ? AND snapshot_status = 'published'
ORDER BY published_at DESC
LIMIT 1
`

type GetLatestPublishedSnapshotByBoardRow struct {
	SnapshotID      string    `json:"snapshot_id"`
	DataWatermarkAt time.Time `json:"data_watermark_at"`
}

func (q *Queries) GetLatestPublishedSnapshotByBoard(ctx context.Context, boardKey string) (GetLatestPublishedSnapshotByBoardRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedSnapshotByBoard, boardKey)
	var i GetLatestPublishedSnapshotByBoardRow
	err := row.Scan(&i.SnapshotID, &i.DataWatermarkAt)
	return i, err
}

const getPendingEmailChallenge = `-- name: GetPendingEmailChallenge :one

SELECT challenge_id, user_id, email_lookup_hash, email_ciphertext, email_key_version,
       challenge_type, code_hash, code_key_version, challenge_status, attempt_count,
       max_attempts, send_count, requested_ip_prefix_hash, expires_at, consumed_at,
       created_at, updated_at
FROM email_challenges
WHERE challenge_type = ? AND email_lookup_hash = ? AND challenge_status = 'pending'
LIMIT 1
`

type GetPendingEmailChallengeParams struct {
	ChallengeType   string `json:"challenge_type"`
	EmailLookupHash []byte `json:"email_lookup_hash"`
}

type GetPendingEmailChallengeRow struct {
	ChallengeID           string         `json:"challenge_id"`
	UserID                sql.NullString `json:"user_id"`
	EmailLookupHash       []byte         `json:"email_lookup_hash"`
	EmailCiphertext       []byte         `json:"email_ciphertext"`
	EmailKeyVersion       uint16         `json:"email_key_version"`
	ChallengeType         string         `json:"challenge_type"`
	CodeHash              []byte         `json:"code_hash"`
	CodeKeyVersion        uint16         `json:"code_key_version"`
	ChallengeStatus       string         `json:"challenge_status"`
	AttemptCount          uint16         `json:"attempt_count"`
	MaxAttempts           uint16         `json:"max_attempts"`
	SendCount             uint16         `json:"send_count"`
	RequestedIpPrefixHash sql.NullString `json:"requested_ip_prefix_hash"`
	ExpiresAt             time.Time      `json:"expires_at"`
	ConsumedAt            sql.NullTime   `json:"consumed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

// Static store queries. Optional-filter query builders remain in reviewed Go call sites.
func (q *Queries) GetPendingEmailChallenge(ctx context.Context, arg GetPendingEmailChallengeParams) (GetPendingEmailChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingEmailChallenge, arg.ChallengeType, arg.EmailLookupHash)
	var i GetPendingEmailChallengeRow
	err := row.Scan(
		&i.ChallengeID,
		&i.UserID,
		&i.EmailLookupHash,
		&i.EmailCiphertext,
		&i.EmailKeyVersion,
		&i.ChallengeType,
		&i.CodeHash,
		&i.CodeKeyVersion,
		&i.ChallengeStatus,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.SendCount,
		&i.RequestedIpPrefixHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrivacyByUser = `-- name: GetPrivacyByUser :one
SELECT p.user_id, p.public_profile_enabled, u.leaderboard_visibility,
       p.show_bio, p.show_token_total, p.show_trends, p.show_activity_calendar,
       p.show_agent_breakdown, p.show_skill_ranking, p.show_achievements,
       p.privacy_version, p.created_at, p.updated_at
FROM user_privacy_settings p
JOIN users u ON u.user_id = p.user_id
WHERE p.user_id = ?
LIMIT 1
`

type GetPrivacyByUserRow struct {
	UserID                string    `json:"user_id"`
	PublicProfileEnabled  bool      `json:"public_profile_enabled"`
	LeaderboardVisibility string    `json:"leaderboard_visibility"`
	ShowBio               bool      `json:"show_bio"`
	ShowTokenTotal        bool      `json:"show_token_total"`
	ShowTrends            bool      `json:"show_trends"`
	ShowActivityCalendar  bool      `json:"show_activity_calendar"`
	ShowAgentBreakdown    bool      `json:"show_agent_breakdown"`
	ShowSkillRanking      bool      `json:"show_skill_ranking"`
	ShowAchievements      bool      `json:"show_achievements"`
	PrivacyVersion        uint64    `json:"privacy_version"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

func (q *Queries) GetPrivacyByUser(ctx context.Context, userID string) (GetPrivacyByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPrivacyByUser, userID)
	var i GetPrivacyByUserRow
	err := row.Scan(
		&i.UserID,
		&i.PublicProfileEnabled,
		&i.LeaderboardVisibility,
		&i.ShowBio,
		&i.ShowTokenTotal,
		&i.ShowTrends,
		&i.ShowActivityCalendar,
		&i.ShowAgentBreakdown,
		&i.ShowSkillRanking,
		&i.ShowAchievements,
		&i.PrivacyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProfileByHandle = `-- name: GetPublishedProfileByHandle :one
SELECT p.user_id, p.handle, p.display_name, p.avatar_url, p.bio, p.profile_status,
       p.show_bio, p.show_token_total, p.show_trends, p.show_activity_calendar,
       p.show_agent_breakdown, p.show_skill_ranking, p.show_achievements,
       p.source_profile_version, p.source_privacy_version, p.projection_version,
       p.published_at, p.created_at, p.updated_at
FROM public_user_profiles p
JOIN users u ON p.user_id = u.user_id
WHERE p.handle = ? AND p.profile_status = 'published' AND u.account_status = 'active'
LIMIT 1
`

func (q *Queries) GetPublishedProfileByHandle(ctx context.Context, handle string) (PublicUserProfile, error) {
	row := q.db.QueryRowContext(ctx, getPublishedProfileByHandle, handle)
	var i PublicUserProfile
	err := row.Scan(
		&i.UserID,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.ProfileStatus,
		&i.ShowBio,
		&i.ShowTokenTotal,
		&i.ShowTrends,
		&i.ShowActivityCalendar,
		&i.ShowAgentBreakdown,
		&i.ShowSkillRanking,
		&i.ShowAchievements,
		&i.SourceProfileVersion,
		&i.SourcePrivacyVersion,
		&i.ProjectionVersion,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadObjectByOwner = `-- name: GetUploadObjectByOwner :one
SELECT object_id, user_id, object_type, object_key, content_type, byte_size,
       content_sha256, image_width, image_height, upload_status, expires_at,
       last_error_code, uploaded_at, ready_at, deleted_at, created_at, updated_at
FROM user_upload_objects
WHERE object_id = ? AND user_id = ?
LIMIT 1
`

type GetUploadObjectByOwnerParams struct {
	ObjectID string `json:"object_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetUploadObjectByOwner(ctx context.Context, arg GetUploadObjectByOwnerParams) (UserUploadObject, error) {
	row := q.db.QueryRowContext(ctx, getUploadObjectByOwner, arg.ObjectID, arg.UserID)
	var i UserUploadObject
	err := row.Scan(
		&i.ObjectID,
		&i.UserID,
		&i.ObjectType,
		&i.ObjectKey,
		&i.ContentType,
		&i.ByteSize,
		&i.ContentSha256,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.UploadStatus,
		&i.ExpiresAt,
		&i.LastErrorCode,
		&i.UploadedAt,
		&i.ReadyAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hidePublicProfileForDeletion = `-- name: HidePublicProfileForDeletion :exec
UPDATE public_user_profiles
SET profile_status = 'hidden', projection_version = projection_version + 1, updated_at = ?
WHERE user_id = ?
`

type HidePublicProfileForDeletionParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	UserID    string    `json:"user_id"`
}

func (q *Queries) HidePublicProfileForDeletion(ctx context.Context, arg HidePublicProfileForDeletionParams) error {
	_, err := q.db.ExecContext(ctx, hidePublicProfileForDeletion, arg.UpdatedAt, arg.UserID)
	return err
}

const listExportJobsByUser = `-- name: ListExportJobsByUser :many
SELECT export_id, user_id, idempotency_key, request_hash, export_scope, export_format,
       filter_json, job_status, attempt_count, next_attempt_at, locked_at, locked_by,
       object_key, file_sha256, file_size, last_error_code, started_at, completed_at,
       expires_at, created_at, updated_at
FROM data_export_jobs
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListExportJobsByUser(ctx context.Context, userID string) ([]DataExportJob, error) {
	rows, err := q.db.QueryContext(ctx, listExportJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataExportJob{}
	for rows.Next() {
		var i DataExportJob
		if err := rows.Scan(
			&i.ExportID,
			&i.UserID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.ExportScope,
			&i.ExportFormat,
			&i.FilterJson,
			&i.JobStatus,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.ObjectKey,
			&i.FileSha256,
			&i.FileSize,
			&i.LastErrorCode,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallationsByUser = `-- name: ListInstallationsByUser :many
SELECT installation_id, user_id, device_public_key, device_name, os_type, os_version,
       architecture, collector_version, installation_status, disabled_at, disabled_reason,
       status_version, registered_at, last_seen_at, revoked_at, updated_at
FROM installations
WHERE user_id = ?
ORDER BY registered_at DESC
`

type ListInstallationsByUserRow struct {
	InstallationID     string         `json:"installation_id"`
	UserID             string         `json:"user_id"`
	DevicePublicKey    []byte         `json:"device_public_key"`
	DeviceName         sql.NullString `json:"device_name"`
	OsType             string         `json:"os_type"`
	OsVersion          sql.NullString `json:"os_version"`
	Architecture       string         `json:"architecture"`
	CollectorVersion   string         `json:"collector_version"`
	InstallationStatus string         `json:"installation_status"`
	DisabledAt         sql.NullTime   `json:"disabled_at"`
	DisabledReason     sql.NullString `json:"disabled_reason"`
	StatusVersion      uint64         `json:"status_version"`
	RegisteredAt       time.Time      `json:"registered_at"`
	LastSeenAt         sql.NullTime   `json:"last_seen_at"`
	RevokedAt          sql.NullTime   `json:"revoked_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

func (q *Queries) ListInstallationsByUser(ctx context.Context, userID string) ([]ListInstallationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstallationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationsByUserRow{}
	for rows.Next() {
		var i ListInstallationsByUserRow
		if err := rows.Scan(
			&i.InstallationID,
			&i.UserID,
			&i.DevicePublicKey,
			&i.DeviceName,
			&i.OsType,
			&i.OsVersion,
			&i.Architecture,
			&i.CollectorVersion,
			&i.InstallationStatus,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.StatusVersion,
			&i.RegisteredAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT session_id, user_id, session_token_hash, csrf_token_hash, credential_version,
       session_status, device_label, user_agent_hash, ip_prefix_hash, last_seen_at,
       idle_expires_at, absolute_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM user_sessions
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]UserSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.SessionTokenHash,
			&i.CsrfTokenHash,
			&i.CredentialVersion,
			&i.SessionStatus,
			&i.DeviceLabel,
			&i.UserAgentHash,
			&i.IpPrefixHash,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleLeaderboardEntries = `-- name: ListVisibleLeaderboardEntries :many
SELECT e.rank_no, p.handle, p.display_name, p.avatar_url, e.metric_value, e.previous_rank_no
FROM leaderboard_entries e
JOIN users u ON e.user_id = u.user_id
JOIN public_user_profiles p ON e.user_id = p.user_id
JOIN user_privacy_settings priv ON e.user_id = priv.user_id
WHERE e.snapshot_id = ? AND u.account_status = 'active'
  AND u.leaderboard_visibility = 'public' AND p.profile_status = 'published'
  AND priv.public_profile_enabled = TRUE
ORDER BY e.rank_no ASC
LIMIT ?
`

type ListVisibleLeaderboardEntriesParams struct {
	SnapshotID string `json:"snapshot_id"`
	Limit      int32  `json:"limit"`
}

type ListVisibleLeaderboardEntriesRow struct {
	RankNo         uint32         `json:"rank_no"`
	Handle         string         `json:"handle"`
	DisplayName    string         `json:"display_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	MetricValue    string         `json:"metric_value"`
	PreviousRankNo sql.NullInt32  `json:"previous_rank_no"`
}

func (q *Queries) ListVisibleLeaderboardEntries(ctx context.Context, arg ListVisibleLeaderboardEntriesParams) ([]ListVisibleLeaderboardEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleLeaderboardEntries, arg.SnapshotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleLeaderboardEntriesRow{}
	for rows.Next() {
		var i ListVisibleLeaderboardEntriesRow
		if err := rows.Scan(
			&i.RankNo,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.MetricValue,
			&i.PreviousRankNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeletionRequestForCancel = `-- name: LockDeletionRequestForCancel :one
SELECT request_status, deletion_scope,
       cancel_before IS NOT NULL AND cancel_before > CURRENT_TIMESTAMP(3) AS cancel_window_open
FROM data_deletion_requests
WHERE request_id = ? AND user_id = ?
FOR UPDATE
`

type LockDeletionRequestForCancelParams struct {
	RequestID string         `json:"request_id"`
	UserID    sql.NullString `json:"user_id"`
}

type LockDeletionRequestForCancelRow struct {
	RequestStatus    string       `json:"request_status"`
	DeletionScope    string       `json:"deletion_scope"`
	CancelWindowOpen sql.NullBool `json:"cancel_window_open"`
}

func (q *Queries) LockDeletionRequestForCancel(ctx context.Context, arg LockDeletionRequestForCancelParams) (LockDeletionRequestForCancelRow, error) {
	row := q.db.QueryRowContext(ctx, lockDeletionRequestForCancel, arg.RequestID, arg.UserID)
	var i LockDeletionRequestForCancelRow
	err := row.Scan(&i.RequestStatus, &i.DeletionScope, &i.CancelWindowOpen)
	return i, err
}

const lockIngestBatch = `-- name: LockIngestBatch :one
SELECT installation_id, request_sha256, accepted_count, duplicate_count, rejected_count, committed_at
FROM ingest_batches
WHERE batch_id = ?
FOR UPDATE
`

type LockIngestBatchRow struct {
	InstallationID string       `json:"installation_id"`
	RequestSha256  []byte       `json:"request_sha256"`
	AcceptedCount  uint32       `json:"accepted_count"`
	DuplicateCount uint32       `json:"duplicate_count"`
	RejectedCount  uint32       `json:"rejected_count"`
	CommittedAt    sql.NullTime `json:"committed_at"`
}

func (q *Queries) LockIngestBatch(ctx context.Context, batchID string) (LockIngestBatchRow, error) {
	row := q.db.QueryRowContext(ctx, lockIngestBatch, batchID)
	var i LockIngestBatchRow
	err := row.Scan(
		&i.InstallationID,
		&i.RequestSha256,
		&i.AcceptedCount,
		&i.DuplicateCount,
		&i.RejectedCount,
		&i.CommittedAt,
	)
	return i, err
}

const lockPrivacyVersion = `-- name: LockPrivacyVersion :one
SELECT privacy_version
FROM user_privacy_settings
WHERE user_id = ?
FOR UPDATE
`

func (q *Queries) LockPrivacyVersion(ctx context.Context, userID string) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockPrivacyVersion, userID)
	var privacy_version uint64
	err := row.Scan(&privacy_version)
	return privacy_version, err
}

const updateEmailChallengeAttempt = `-- name: UpdateEmailChallengeAttempt :execrows
UPDATE email_challenges
SET attempt_count = ?, challenge_status = ?, updated_at = ?
WHERE challenge_id = ?
`

type UpdateEmailChallengeAttemptParams struct {
	AttemptCount    uint16    `json:"attempt_count"`
	ChallengeStatus string    `json:"challenge_status"`
	UpdatedAt       time.Time `json:"updated_at"`
	ChallengeID     string    `json:"challenge_id"`
}

func (q *Queries) UpdateEmailChallengeAttempt(ctx context.Context, arg UpdateEmailChallengeAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEmailChallengeAttempt,
		arg.AttemptCount,
		arg.ChallengeStatus,
		arg.UpdatedAt,
		arg.ChallengeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInstallationLastSeen = `-- name: UpdateInstallationLastSeen :exec
UPDATE installations
SET last_seen_at = ?, updated_at = ?
WHERE installation_id = ?
`

type UpdateInstallationLastSeenParams struct {
	LastSeenAt     sql.NullTime `json:"last_seen_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	InstallationID string       `json:"installation_id"`
}

func (q *Queries) UpdateInstallationLastSeen(ctx context.Context, arg UpdateInstallationLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateInstallationLastSeen, arg.LastSeenAt, arg.UpdatedAt, arg.InstallationID)
	return err
}

const updateUploadObjectStatus = `-- name: UpdateUploadObjectStatus :execrows
UPDATE user_upload_objects
SET upload_status = ?, last_error_code = ?, updated_at = ?
WHERE object_id = ?
`

type UpdateUploadObjectStatusParams struct {
	UploadStatus  string         `json:"upload_status"`
	LastErrorCode sql.NullString `json:"last_error_code"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ObjectID      string         `json:"object_id"`
}

func (q *Queries) UpdateUploadObjectStatus(ctx context.Context, arg UpdateUploadObjectStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUploadObjectStatus,
		arg.UploadStatus,
		arg.LastErrorCode,
		arg.UpdatedAt,
		arg.ObjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
