// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, auth_subject_hash, email_lookup_hash, email_ciphertext,
       handle, email_verified_at, display_name, avatar_url, avatar_object_id,
       bio, account_status, leaderboard_visibility, timezone_name, locale,
       onboarding_completed_at, profile_version, public_profile_updated_at,
       created_at, updated_at, deleted_at
FROM users
WHERE user_id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	UserID                 string         `json:"user_id"`
	AuthSubjectHash        []byte         `json:"auth_subject_hash"`
	EmailLookupHash        sql.NullString `json:"email_lookup_hash"`
	EmailCiphertext        sql.NullString `json:"email_ciphertext"`
	Handle                 sql.NullString `json:"handle"`
	EmailVerifiedAt        sql.NullTime   `json:"email_verified_at"`
	DisplayName            string         `json:"display_name"`
	AvatarUrl              sql.NullString `json:"avatar_url"`
	AvatarObjectID         sql.NullString `json:"avatar_object_id"`
	Bio                    sql.NullString `json:"bio"`
	AccountStatus          string         `json:"account_status"`
	LeaderboardVisibility  string         `json:"leaderboard_visibility"`
	TimezoneName           string         `json:"timezone_name"`
	Locale                 string         `json:"locale"`
	OnboardingCompletedAt  sql.NullTime   `json:"onboarding_completed_at"`
	ProfileVersion         uint64         `json:"profile_version"`
	PublicProfileUpdatedAt sql.NullTime   `json:"public_profile_updated_at"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.AuthSubjectHash,
		&i.EmailLookupHash,
		&i.EmailCiphertext,
		&i.Handle,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AvatarObjectID,
		&i.Bio,
		&i.AccountStatus,
		&i.LeaderboardVisibility,
		&i.TimezoneName,
		&i.Locale,
		&i.OnboardingCompletedAt,
		&i.ProfileVersion,
		&i.PublicProfileUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
