// Generated by tools/generate-protocol.mjs from schemas/protocol/v1/spec.json.
// Do not edit manually.

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: &str = "1.0";
pub type UInt64String = String;
pub type DecimalString = String;
pub type HmacSha256 = String;
pub type Base64Url32 = String;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AdapterRuntimeStatus {
    #[serde(rename = "UNDETECTED")]
    Undetected,
    #[serde(rename = "DETECTED")]
    Detected,
    #[serde(rename = "NEEDS_PERMISSION")]
    NeedsPermission,
    #[serde(rename = "CONFIGURING")]
    Configuring,
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DEGRADED")]
    Degraded,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "DISABLED")]
    Disabled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetupPlanStatus {
    #[serde(rename = "PROPOSED")]
    Proposed,
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "APPLYING")]
    Applying,
    #[serde(rename = "VERIFYING")]
    Verifying,
    #[serde(rename = "APPLIED")]
    Applied,
    #[serde(rename = "ROLLING_BACK")]
    RollingBack,
    #[serde(rename = "ROLLED_BACK")]
    RolledBack,
    #[serde(rename = "FAILED")]
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SourceCheckpointStatus {
    #[serde(rename = "DISCOVERED")]
    Discovered,
    #[serde(rename = "SCANNING")]
    Scanning,
    #[serde(rename = "CURRENT")]
    Current,
    #[serde(rename = "STALE")]
    Stale,
    #[serde(rename = "ROTATED")]
    Rotated,
    #[serde(rename = "TRUNCATED")]
    Truncated,
    #[serde(rename = "PERMISSION_DENIED")]
    PermissionDenied,
    #[serde(rename = "INCOMPATIBLE")]
    Incompatible,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "DISABLED")]
    Disabled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventDeliveryStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "IN_FLIGHT")]
    InFlight,
    #[serde(rename = "ACKED")]
    Acked,
    #[serde(rename = "RETRYABLE")]
    Retryable,
    #[serde(rename = "DEAD_LETTER")]
    DeadLetter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ClientUploadBatchStatus {
    #[serde(rename = "BUILDING")]
    Building,
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "IN_FLIGHT")]
    InFlight,
    #[serde(rename = "ACKED")]
    Acked,
    #[serde(rename = "PARTIALLY_ACKED")]
    PartiallyAcked,
    #[serde(rename = "RETRYABLE")]
    Retryable,
    #[serde(rename = "FAILED")]
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Accuracy {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "derived")]
    Derived,
    #[serde(rename = "correlated")]
    Correlated,
    #[serde(rename = "estimated")]
    Estimated,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CapabilityAvailability {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "unavailable")]
    Unavailable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Capability {
    #[serde(rename = "tokens")]
    Tokens,
    #[serde(rename = "sessions")]
    Sessions,
    #[serde(rename = "turns")]
    Turns,
    #[serde(rename = "tools")]
    Tools,
    #[serde(rename = "skills")]
    Skills,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "cost")]
    Cost,
    #[serde(rename = "subagents")]
    Subagents,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SourceKind {
    #[serde(rename = "otlp")]
    Otlp,
    #[serde(rename = "jsonl_tail")]
    JsonlTail,
    #[serde(rename = "sqlite_snapshot")]
    SqliteSnapshot,
    #[serde(rename = "file_snapshot")]
    FileSnapshot,
    #[serde(rename = "runtime_stream")]
    RuntimeStream,
    #[serde(rename = "local_http_api")]
    LocalHttpApi,
    #[serde(rename = "command_snapshot")]
    CommandSnapshot,
    #[serde(rename = "remote_api")]
    RemoteApi,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "session_started")]
    SessionStarted,
    #[serde(rename = "session_ended")]
    SessionEnded,
    #[serde(rename = "turn_started")]
    TurnStarted,
    #[serde(rename = "turn_completed")]
    TurnCompleted,
    #[serde(rename = "model_usage_recorded")]
    ModelUsageRecorded,
    #[serde(rename = "tool_invoked")]
    ToolInvoked,
    #[serde(rename = "skill_invoked")]
    SkillInvoked,
    #[serde(rename = "code_changed")]
    CodeChanged,
    #[serde(rename = "cost_recorded")]
    CostRecorded,
    #[serde(rename = "agent_spawned")]
    AgentSpawned,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CostSource {
    #[serde(rename = "provider_reported")]
    ProviderReported,
    #[serde(rename = "estimated_price_table")]
    EstimatedPriceTable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SkillInvokeType {
    #[serde(rename = "native")]
    Native,
    #[serde(rename = "hook")]
    Hook,
    #[serde(rename = "tool_correlated")]
    ToolCorrelated,
    #[serde(rename = "runtime_correlated")]
    RuntimeCorrelated,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SessionEndReason {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TurnTrigger {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "subagent")]
    Subagent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "windows-x64")]
    WindowsX64,
    #[serde(rename = "windows-arm64")]
    WindowsArm64,
    #[serde(rename = "macos-x64")]
    MacosX64,
    #[serde(rename = "macos-arm64")]
    MacosArm64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OsType {
    #[serde(rename = "windows")]
    Windows,
    #[serde(rename = "macos")]
    Macos,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Architecture {
    #[serde(rename = "x86_64")]
    X8664,
    #[serde(rename = "aarch64")]
    Aarch64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PathTemplateId {
    #[serde(rename = "USER_HOME")]
    UserHome,
    #[serde(rename = "LOCAL_APP_DATA")]
    LocalAppData,
    #[serde(rename = "ROAMING_APP_DATA")]
    RoamingAppData,
    #[serde(rename = "MAC_APP_SUPPORT")]
    MacAppSupport,
    #[serde(rename = "CODEX_HOME")]
    CodexHome,
    #[serde(rename = "AGENT_CONFIG_HOME")]
    AgentConfigHome,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PathAccess {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RejectedEventErrorCode {
    #[serde(rename = "SCHEMA_INVALID")]
    SchemaInvalid,
    #[serde(rename = "PRIVACY_REJECTED")]
    PrivacyRejected,
    #[serde(rename = "EVENT_TOO_LARGE")]
    EventTooLarge,
    #[serde(rename = "UNSUPPORTED_VERSION")]
    UnsupportedVersion,
    #[serde(rename = "INTERNAL_RETRYABLE")]
    InternalRetryable,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventSource {
    pub kind: SourceKind,
    pub cursor_hmac: HmacSha256,
    pub raw_fingerprint_hmac: HmacSha256,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TokenUsage {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_tokens: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_tokens: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionStartedPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_hash: Option<HmacSha256>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionEndedPayload {
    pub reason: SessionEndReason,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TurnStartedPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trigger: Option<TurnTrigger>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TurnCompletedPayload {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_class: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ModelUsageRecordedPayload {
    pub provider_id: String,
    pub model_id: String,
    pub tokens: TokenUsage,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ToolInvokedPayload {
    pub tool_category: String,
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillInvokedPayload {
    pub skill_key: HmacSha256,
    pub invoke_type: SkillInvokeType,
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_key: Option<HmacSha256>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CodeChangedPayload {
    pub added_lines: UInt64String,
    pub removed_lines: UInt64String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_lines: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted_lines: Option<UInt64String>,
    pub file_count: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CostRecordedPayload {
    pub amount: DecimalString,
    pub currency: String,
    pub source: CostSource,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<DecimalString>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentSpawnedPayload {
    pub child_session_hash: HmacSha256,
    pub spawned_agent_type: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventEnvelope {
    pub schema_version: String,
    pub event_id: Base64Url32,
    pub adapter_id: String,
    pub adapter_version: String,
    pub agent_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_version: Option<String>,
    pub installation_id: String,
    pub occurred_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_hash: Option<HmacSha256>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_hash: Option<HmacSha256>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_hash: Option<HmacSha256>,
    pub source: EventSource,
    pub accuracy: Accuracy,
    pub payload: EventPayload,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentDescriptor {
    pub id: String,
    pub version_range: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PathPermission {
    pub template: PathTemplateId,
    pub relative_glob: String,
    pub access: PathAccess,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CommandPermission {
    pub executable_id: String,
    pub args: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AdapterPermissions {
    pub read_paths: Vec<PathPermission>,
    pub write_paths: Vec<PathPermission>,
    pub commands: Vec<CommandPermission>,
    pub network_domains: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AdapterManifest {
    #[serde(rename = "$schema")]
    pub schema: String,
    pub manifest_version: String,
    pub id: String,
    pub name: String,
    pub version: String,
    pub protocol_version: String,
    pub agent: AgentDescriptor,
    pub platforms: Vec<Platform>,
    pub sources: Vec<SourceKind>,
    pub permissions: AdapterPermissions,
    pub capabilities: Vec<Capability>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct UploadBatch {
    pub batch_id: String,
    pub installation_id: String,
    pub created_at: String,
    pub events: Vec<EventEnvelope>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RejectedEvent {
    pub event_id: Base64Url32,
    pub error_code: RejectedEventErrorCode,
    pub retryable: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct UploadAck {
    pub batch_id: String,
    pub accepted: u32,
    pub duplicates: u32,
    pub rejected: Vec<RejectedEvent>,
    pub server_time: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct UploadPolicy {
    pub max_batch_events: u32,
    pub max_batch_bytes: u32,
    pub flush_interval_seconds: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InstallationRegisterRequest {
    pub device_public_key: Base64Url32,
    pub os_type: OsType,
    pub architecture: Architecture,
    pub collector_version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InstallationRegisterResponse {
    pub installation_id: String,
    pub policy: UploadPolicy,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CapabilityStatus {
    pub capability: Capability,
    pub availability: CapabilityAvailability,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<Accuracy>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe_reason_code: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AdapterStatusReport {
    pub adapter_id: String,
    pub adapter_version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_version: Option<String>,
    pub runtime_status: AdapterRuntimeStatus,
    pub capabilities: Vec<CapabilityStatus>,
    pub source_kinds: Vec<SourceKind>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe_error_code: Option<String>,
    pub reported_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EventPayload {
    #[serde(rename = "session_started")]
    SessionStarted(SessionStartedPayload),
    #[serde(rename = "session_ended")]
    SessionEnded(SessionEndedPayload),
    #[serde(rename = "turn_started")]
    TurnStarted(TurnStartedPayload),
    #[serde(rename = "turn_completed")]
    TurnCompleted(TurnCompletedPayload),
    #[serde(rename = "model_usage_recorded")]
    ModelUsageRecorded(ModelUsageRecordedPayload),
    #[serde(rename = "tool_invoked")]
    ToolInvoked(ToolInvokedPayload),
    #[serde(rename = "skill_invoked")]
    SkillInvoked(SkillInvokedPayload),
    #[serde(rename = "code_changed")]
    CodeChanged(CodeChangedPayload),
    #[serde(rename = "cost_recorded")]
    CostRecorded(CostRecordedPayload),
    #[serde(rename = "agent_spawned")]
    AgentSpawned(AgentSpawnedPayload),
}

