// Generated by tools/generate-protocol.mjs from schemas/protocol/v2/spec.json.
// Do not edit manually.

export const PROTOCOL_VERSION = "2.0" as const;
export const PROTOCOL_VERSION_NUMBER = 2 as const;
export const SCHEMA_VERSION = 2 as const;
export const METRIC_SEMANTICS_VERSION = 1 as const;
export const DEFAULT_MAX_BATCH_EVENTS = 500 as const;
export const DEFAULT_MAX_BATCH_BYTES = 1048576 as const;
export type UInt64String = string;
export type DecimalString = string;
export type HmacSha256 = string;
export type Base64Url32 = string;

export const EventTypeValues = ["model_usage_recorded","cost_recorded","session_started","session_ended","turn_started","turn_completed","tool_invoked","skill_invoked","code_changed"] as const;
export type EventType = (typeof EventTypeValues)[number];

export const AckResultValues = ["accepted","duplicate","discarded","retry","blocked","conflict","invalid"] as const;
export type AckResult = (typeof AckResultValues)[number];

export const AccuracyValues = ["exact","derived","correlated","estimated"] as const;
export type Accuracy = (typeof AccuracyValues)[number];

export const TimeSourceValues = ["source_record","prior_record","file_mtime","unknown"] as const;
export type TimeSource = (typeof TimeSourceValues)[number];

export const CostSourceValues = ["provider_reported","calculated_price"] as const;
export type CostSource = (typeof CostSourceValues)[number];

export const TurnTriggerValues = ["user","system","scheduled","subagent"] as const;
export type TurnTrigger = (typeof TurnTriggerValues)[number];

export const SessionEndReasonValues = ["completed","cancelled","error","timeout","unknown"] as const;
export type SessionEndReason = (typeof SessionEndReasonValues)[number];

export const AckErrorCodeValues = ["outside_window","deleted","future_event_time","unsupported_version","schema_invalid","hash_mismatch","negative_count","unknown_field","duplicate_key","dependency_expired","internal_retryable"] as const;
export type AckErrorCode = (typeof AckErrorCodeValues)[number];

export interface ModelRef {
  providerId: string
  modelId: string
}

export interface SkillRef {
  skillKey: Base64Url32
  publicName?: string
}

export interface UsagePayload {
  token_total?: UInt64String
  input_context_tokens?: UInt64String
  output_tokens?: UInt64String
  cache_read_tokens?: UInt64String
  cache_write_tokens?: UInt64String
  reasoning_tokens?: UInt64String
  request_count?: UInt64String
}

export interface CostPayload {
  units: UInt64String
  currency: string
  source: CostSource
  price_basis_id?: string
  coverage?: string
}

export interface CodePayload {
  generated?: UInt64String
  accepted?: UInt64String
  added?: UInt64String
  removed?: UInt64String
  file_touch_count?: UInt64String
}

export interface ActivityPayload {
  duration_ms?: UInt64String
  success?: boolean
  trigger?: TurnTrigger
  reason?: SessionEndReason
  tool_category?: string
}

export interface ContextPayload {
  parent_session_key?: Base64Url32
  tool_call_key?: Base64Url32
  scope_started_at?: UInt64String
  coverage?: string
}

export interface MetaPayload {
  accuracy: Accuracy
  time_source: TimeSource
  safe_tags?: Array<string>
}

export interface EventPayload {
  usage?: UsagePayload
  cost?: CostPayload
  code?: CodePayload
  activity?: ActivityPayload
  context?: ContextPayload
  meta?: MetaPayload
}

export interface EventEnvelope {
  eventId: Base64Url32
  factKey: Base64Url32
  factRevision: UInt64String
  schemaVersion: number
  metricSemanticsVersion: number
  harnessId: string
  eventType: EventType
  occurredAt: UInt64String
  model?: ModelRef
  skill?: SkillRef
  sessionKey?: Base64Url32
  turnKey?: Base64Url32
  costScopeKey?: Base64Url32
  payload: EventPayload
  contentHash: Base64Url32
}

export interface TelemetryEventsRequest {
  protocolVersion: number
  requestId: string
  events: Array<EventEnvelope>
}

export interface EventAck {
  eventId: Base64Url32
  contentHash: Base64Url32
  result: AckResult
  code?: AckErrorCode
}

export interface TelemetryEventsResponse {
  requestId: string
  serverTimeMs: UInt64String
  acks: Array<EventAck>
}

export interface TelemetryCapabilities {
  protocolVersion: number
  supportedSchemaVersions: Array<number>
  supportedMetricSemanticsVersions: Array<number>
  maxBatchEvents: number
  maxBatchBytes: number
  serverTimeMs: UInt64String
  eventReceiveLowerBoundMs: UInt64String
}

