// Code generated by tools/generate-protocol.mjs; DO NOT EDIT.

package protocol

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

const ProtocolVersion = "1.0"

type UInt64String string
type DecimalString string
type HmacSha256 string
type Base64Url32 string

type AdapterRuntimeStatus string

const (
	AdapterRuntimeStatusUndetected      AdapterRuntimeStatus = "UNDETECTED"
	AdapterRuntimeStatusDetected        AdapterRuntimeStatus = "DETECTED"
	AdapterRuntimeStatusNeedsPermission AdapterRuntimeStatus = "NEEDS_PERMISSION"
	AdapterRuntimeStatusConfiguring     AdapterRuntimeStatus = "CONFIGURING"
	AdapterRuntimeStatusActive          AdapterRuntimeStatus = "ACTIVE"
	AdapterRuntimeStatusDegraded        AdapterRuntimeStatus = "DEGRADED"
	AdapterRuntimeStatusError           AdapterRuntimeStatus = "ERROR"
	AdapterRuntimeStatusDisabled        AdapterRuntimeStatus = "DISABLED"
)

type SetupPlanStatus string

const (
	SetupPlanStatusProposed    SetupPlanStatus = "PROPOSED"
	SetupPlanStatusApproved    SetupPlanStatus = "APPROVED"
	SetupPlanStatusApplying    SetupPlanStatus = "APPLYING"
	SetupPlanStatusVerifying   SetupPlanStatus = "VERIFYING"
	SetupPlanStatusApplied     SetupPlanStatus = "APPLIED"
	SetupPlanStatusRollingBack SetupPlanStatus = "ROLLING_BACK"
	SetupPlanStatusRolledBack  SetupPlanStatus = "ROLLED_BACK"
	SetupPlanStatusFailed      SetupPlanStatus = "FAILED"
)

type SourceCheckpointStatus string

const (
	SourceCheckpointStatusDiscovered       SourceCheckpointStatus = "DISCOVERED"
	SourceCheckpointStatusScanning         SourceCheckpointStatus = "SCANNING"
	SourceCheckpointStatusCurrent          SourceCheckpointStatus = "CURRENT"
	SourceCheckpointStatusStale            SourceCheckpointStatus = "STALE"
	SourceCheckpointStatusRotated          SourceCheckpointStatus = "ROTATED"
	SourceCheckpointStatusTruncated        SourceCheckpointStatus = "TRUNCATED"
	SourceCheckpointStatusPermissionDenied SourceCheckpointStatus = "PERMISSION_DENIED"
	SourceCheckpointStatusIncompatible     SourceCheckpointStatus = "INCOMPATIBLE"
	SourceCheckpointStatusError            SourceCheckpointStatus = "ERROR"
	SourceCheckpointStatusDisabled         SourceCheckpointStatus = "DISABLED"
)

type EventDeliveryStatus string

const (
	EventDeliveryStatusPending    EventDeliveryStatus = "PENDING"
	EventDeliveryStatusQueued     EventDeliveryStatus = "QUEUED"
	EventDeliveryStatusInFlight   EventDeliveryStatus = "IN_FLIGHT"
	EventDeliveryStatusAcked      EventDeliveryStatus = "ACKED"
	EventDeliveryStatusRetryable  EventDeliveryStatus = "RETRYABLE"
	EventDeliveryStatusDeadLetter EventDeliveryStatus = "DEAD_LETTER"
)

type ClientUploadBatchStatus string

const (
	ClientUploadBatchStatusBuilding       ClientUploadBatchStatus = "BUILDING"
	ClientUploadBatchStatusReady          ClientUploadBatchStatus = "READY"
	ClientUploadBatchStatusInFlight       ClientUploadBatchStatus = "IN_FLIGHT"
	ClientUploadBatchStatusAcked          ClientUploadBatchStatus = "ACKED"
	ClientUploadBatchStatusPartiallyAcked ClientUploadBatchStatus = "PARTIALLY_ACKED"
	ClientUploadBatchStatusRetryable      ClientUploadBatchStatus = "RETRYABLE"
	ClientUploadBatchStatusFailed         ClientUploadBatchStatus = "FAILED"
)

type Accuracy string

const (
	AccuracyExact      Accuracy = "exact"
	AccuracyDerived    Accuracy = "derived"
	AccuracyCorrelated Accuracy = "correlated"
	AccuracyEstimated  Accuracy = "estimated"
)

type CapabilityAvailability string

const (
	CapabilityAvailabilityAvailable   CapabilityAvailability = "available"
	CapabilityAvailabilityUnavailable CapabilityAvailability = "unavailable"
)

type Capability string

const (
	CapabilityTokens    Capability = "tokens"
	CapabilitySessions  Capability = "sessions"
	CapabilityTurns     Capability = "turns"
	CapabilityTools     Capability = "tools"
	CapabilitySkills    Capability = "skills"
	CapabilityCode      Capability = "code"
	CapabilityCost      Capability = "cost"
	CapabilitySubagents Capability = "subagents"
)

type SourceKind string

const (
	SourceKindOtlp            SourceKind = "otlp"
	SourceKindJsonlTail       SourceKind = "jsonl_tail"
	SourceKindSqliteSnapshot  SourceKind = "sqlite_snapshot"
	SourceKindFileSnapshot    SourceKind = "file_snapshot"
	SourceKindRuntimeStream   SourceKind = "runtime_stream"
	SourceKindLocalHttpApi    SourceKind = "local_http_api"
	SourceKindCommandSnapshot SourceKind = "command_snapshot"
	SourceKindRemoteApi       SourceKind = "remote_api"
)

type EventType string

const (
	EventTypeSessionStarted     EventType = "session_started"
	EventTypeSessionEnded       EventType = "session_ended"
	EventTypeTurnStarted        EventType = "turn_started"
	EventTypeTurnCompleted      EventType = "turn_completed"
	EventTypeModelUsageRecorded EventType = "model_usage_recorded"
	EventTypeToolInvoked        EventType = "tool_invoked"
	EventTypeSkillInvoked       EventType = "skill_invoked"
	EventTypeCodeChanged        EventType = "code_changed"
	EventTypeCostRecorded       EventType = "cost_recorded"
	EventTypeAgentSpawned       EventType = "agent_spawned"
)

type CostSource string

const (
	CostSourceProviderReported    CostSource = "provider_reported"
	CostSourceEstimatedPriceTable CostSource = "estimated_price_table"
)

type SkillInvokeType string

const (
	SkillInvokeTypeNative            SkillInvokeType = "native"
	SkillInvokeTypeHook              SkillInvokeType = "hook"
	SkillInvokeTypeToolCorrelated    SkillInvokeType = "tool_correlated"
	SkillInvokeTypeRuntimeCorrelated SkillInvokeType = "runtime_correlated"
)

type SessionEndReason string

const (
	SessionEndReasonCompleted SessionEndReason = "completed"
	SessionEndReasonCancelled SessionEndReason = "cancelled"
	SessionEndReasonError     SessionEndReason = "error"
	SessionEndReasonTimeout   SessionEndReason = "timeout"
	SessionEndReasonUnknown   SessionEndReason = "unknown"
)

type TurnTrigger string

const (
	TurnTriggerUser      TurnTrigger = "user"
	TurnTriggerSystem    TurnTrigger = "system"
	TurnTriggerScheduled TurnTrigger = "scheduled"
	TurnTriggerSubagent  TurnTrigger = "subagent"
)

type Platform string

const (
	PlatformWindowsX64   Platform = "windows-x64"
	PlatformWindowsArm64 Platform = "windows-arm64"
	PlatformMacosX64     Platform = "macos-x64"
	PlatformMacosArm64   Platform = "macos-arm64"
)

type OsType string

const (
	OsTypeWindows OsType = "windows"
	OsTypeMacos   OsType = "macos"
)

type Architecture string

const (
	ArchitectureX8664   Architecture = "x86_64"
	ArchitectureAarch64 Architecture = "aarch64"
)

type PathTemplateId string

const (
	PathTemplateIdUserHome        PathTemplateId = "USER_HOME"
	PathTemplateIdLocalAppData    PathTemplateId = "LOCAL_APP_DATA"
	PathTemplateIdRoamingAppData  PathTemplateId = "ROAMING_APP_DATA"
	PathTemplateIdMacAppSupport   PathTemplateId = "MAC_APP_SUPPORT"
	PathTemplateIdCodexHome       PathTemplateId = "CODEX_HOME"
	PathTemplateIdAgentConfigHome PathTemplateId = "AGENT_CONFIG_HOME"
)

type PathAccess string

const (
	PathAccessRead  PathAccess = "read"
	PathAccessWrite PathAccess = "write"
)

type RejectedEventErrorCode string

const (
	RejectedEventErrorCodeSchemaInvalid      RejectedEventErrorCode = "SCHEMA_INVALID"
	RejectedEventErrorCodePrivacyRejected    RejectedEventErrorCode = "PRIVACY_REJECTED"
	RejectedEventErrorCodeEventTooLarge      RejectedEventErrorCode = "EVENT_TOO_LARGE"
	RejectedEventErrorCodeUnsupportedVersion RejectedEventErrorCode = "UNSUPPORTED_VERSION"
	RejectedEventErrorCodeInternalRetryable  RejectedEventErrorCode = "INTERNAL_RETRYABLE"
)

type EventSource struct {
	Kind               SourceKind `json:"kind"`
	CursorHMAC         HmacSha256 `json:"cursorHmac"`
	RawFingerprintHMAC HmacSha256 `json:"rawFingerprintHmac"`
}

type TokenUsage struct {
	InputTokens      *UInt64String `json:"inputTokens,omitempty"`
	OutputTokens     *UInt64String `json:"outputTokens,omitempty"`
	CacheReadTokens  *UInt64String `json:"cacheReadTokens,omitempty"`
	CacheWriteTokens *UInt64String `json:"cacheWriteTokens,omitempty"`
	ReasoningTokens  *UInt64String `json:"reasoningTokens,omitempty"`
	ToolTokens       *UInt64String `json:"toolTokens,omitempty"`
	TotalTokens      *UInt64String `json:"totalTokens,omitempty"`
}

type SessionStartedPayload struct {
	Type          EventType   `json:"type"`
	ModelID       *string     `json:"modelId,omitempty"`
	WorkspaceHash *HmacSha256 `json:"workspaceHash,omitempty"`
}

type SessionEndedPayload struct {
	Type       EventType        `json:"type"`
	Reason     SessionEndReason `json:"reason"`
	DurationMs *UInt64String    `json:"durationMs,omitempty"`
}

type TurnStartedPayload struct {
	Type    EventType    `json:"type"`
	Trigger *TurnTrigger `json:"trigger,omitempty"`
}

type TurnCompletedPayload struct {
	Type       EventType     `json:"type"`
	Success    bool          `json:"success"`
	DurationMs *UInt64String `json:"durationMs,omitempty"`
	ErrorClass *string       `json:"errorClass,omitempty"`
}

type ModelUsageRecordedPayload struct {
	Type       EventType  `json:"type"`
	ProviderID string     `json:"providerId"`
	ModelID    string     `json:"modelId"`
	Tokens     TokenUsage `json:"tokens"`
}

type ToolInvokedPayload struct {
	Type         EventType     `json:"type"`
	ToolCategory string        `json:"toolCategory"`
	Success      bool          `json:"success"`
	DurationMs   *UInt64String `json:"durationMs,omitempty"`
}

type SkillInvokedPayload struct {
	Type       EventType       `json:"type"`
	SkillKey   HmacSha256      `json:"skillKey"`
	InvokeType SkillInvokeType `json:"invokeType"`
	Success    bool            `json:"success"`
	PluginKey  *HmacSha256     `json:"pluginKey,omitempty"`
	DurationMs *UInt64String   `json:"durationMs,omitempty"`
}

type CodeChangedPayload struct {
	Type           EventType     `json:"type"`
	AddedLines     UInt64String  `json:"addedLines"`
	RemovedLines   UInt64String  `json:"removedLines"`
	GeneratedLines *UInt64String `json:"generatedLines,omitempty"`
	AcceptedLines  *UInt64String `json:"acceptedLines,omitempty"`
	FileCount      uint32        `json:"fileCount"`
	Language       *string       `json:"language,omitempty"`
}

type CostRecordedPayload struct {
	Type           EventType      `json:"type"`
	Amount         DecimalString  `json:"amount"`
	Currency       string         `json:"currency"`
	Source         CostSource     `json:"source"`
	DiscountAmount *DecimalString `json:"discountAmount,omitempty"`
}

type AgentSpawnedPayload struct {
	Type             EventType  `json:"type"`
	ChildSessionHash HmacSha256 `json:"childSessionHash"`
	SpawnedAgentType string     `json:"spawnedAgentType"`
}

type EventEnvelope struct {
	SchemaVersion  string       `json:"schemaVersion"`
	EventID        Base64Url32  `json:"eventId"`
	AdapterID      string       `json:"adapterId"`
	AdapterVersion string       `json:"adapterVersion"`
	AgentID        string       `json:"agentId"`
	AgentVersion   *string      `json:"agentVersion,omitempty"`
	InstallationID string       `json:"installationId"`
	OccurredAt     string       `json:"occurredAt"`
	SessionHash    *HmacSha256  `json:"sessionHash,omitempty"`
	TurnHash       *HmacSha256  `json:"turnHash,omitempty"`
	ToolCallHash   *HmacSha256  `json:"toolCallHash,omitempty"`
	Source         EventSource  `json:"source"`
	Accuracy       Accuracy     `json:"accuracy"`
	Payload        EventPayload `json:"payload"`
}

type AgentDescriptor struct {
	ID           string `json:"id"`
	VersionRange string `json:"versionRange"`
}

type PathPermission struct {
	Template     PathTemplateId `json:"template"`
	RelativeGlob string         `json:"relativeGlob"`
	Access       PathAccess     `json:"access"`
}

type CommandPermission struct {
	ExecutableID string   `json:"executableId"`
	Args         []string `json:"args"`
}

type AdapterPermissions struct {
	ReadPaths      []PathPermission    `json:"readPaths"`
	WritePaths     []PathPermission    `json:"writePaths"`
	Commands       []CommandPermission `json:"commands"`
	NetworkDomains []string            `json:"networkDomains"`
}

type AdapterManifest struct {
	Schema          string             `json:"$schema"`
	ManifestVersion string             `json:"manifestVersion"`
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	ProtocolVersion string             `json:"protocolVersion"`
	Agent           AgentDescriptor    `json:"agent"`
	Platforms       []Platform         `json:"platforms"`
	Sources         []SourceKind       `json:"sources"`
	Permissions     AdapterPermissions `json:"permissions"`
	Capabilities    []Capability       `json:"capabilities"`
}

type UploadBatch struct {
	BatchID        string          `json:"batchId"`
	InstallationID string          `json:"installationId"`
	CreatedAt      string          `json:"createdAt"`
	Events         []EventEnvelope `json:"events"`
}

type RejectedEvent struct {
	EventID   Base64Url32            `json:"eventId"`
	ErrorCode RejectedEventErrorCode `json:"errorCode"`
	Retryable bool                   `json:"retryable"`
}

type UploadAck struct {
	BatchID    string          `json:"batchId"`
	Accepted   uint32          `json:"accepted"`
	Duplicates uint32          `json:"duplicates"`
	Rejected   []RejectedEvent `json:"rejected"`
	ServerTime string          `json:"serverTime"`
}

type UploadPolicy struct {
	MaxBatchEvents       uint32 `json:"maxBatchEvents"`
	MaxBatchBytes        uint32 `json:"maxBatchBytes"`
	FlushIntervalSeconds uint32 `json:"flushIntervalSeconds"`
}

type InstallationRegisterRequest struct {
	DevicePublicKey  Base64Url32  `json:"devicePublicKey"`
	OsType           OsType       `json:"osType"`
	Architecture     Architecture `json:"architecture"`
	CollectorVersion string       `json:"collectorVersion"`
}

type InstallationRegisterResponse struct {
	InstallationID string       `json:"installationId"`
	Policy         UploadPolicy `json:"policy"`
}

type CapabilityStatus struct {
	Capability     Capability             `json:"capability"`
	Availability   CapabilityAvailability `json:"availability"`
	Accuracy       *Accuracy              `json:"accuracy,omitempty"`
	SafeReasonCode *string                `json:"safeReasonCode,omitempty"`
}

type AdapterStatusReport struct {
	AdapterID      string               `json:"adapterId"`
	AdapterVersion string               `json:"adapterVersion"`
	AgentVersion   *string              `json:"agentVersion,omitempty"`
	RuntimeStatus  AdapterRuntimeStatus `json:"runtimeStatus"`
	Capabilities   []CapabilityStatus   `json:"capabilities"`
	SourceKinds    []SourceKind         `json:"sourceKinds"`
	SafeErrorCode  *string              `json:"safeErrorCode,omitempty"`
	ReportedAt     string               `json:"reportedAt"`
}

type EventPayload struct{ Value any }

func (p *EventPayload) UnmarshalJSON(data []byte) error {
	var discriminator struct {
		Type EventType `json:"type"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return err
	}
	decode := func(target any) error {
		d := json.NewDecoder(bytes.NewReader(data))
		d.DisallowUnknownFields()
		if err := d.Decode(target); err != nil {
			return err
		}
		if err := d.Decode(&struct{}{}); err != io.EOF {
			return fmt.Errorf("trailing JSON")
		}
		return nil
	}
	switch discriminator.Type {
	case EventTypeSessionStarted:
		var value SessionStartedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeSessionEnded:
		var value SessionEndedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeTurnStarted:
		var value TurnStartedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeTurnCompleted:
		var value TurnCompletedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeModelUsageRecorded:
		var value ModelUsageRecordedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeToolInvoked:
		var value ToolInvokedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeSkillInvoked:
		var value SkillInvokedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeCodeChanged:
		var value CodeChangedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeCostRecorded:
		var value CostRecordedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	case EventTypeAgentSpawned:
		var value AgentSpawnedPayload
		if err := decode(&value); err != nil {
			return err
		}
		p.Value = value
	default:
		return fmt.Errorf("unsupported event payload type %q", discriminator.Type)
	}
	return nil
}

func (p EventPayload) MarshalJSON() ([]byte, error) {
	if p.Value == nil {
		return nil, fmt.Errorf("event payload is nil")
	}
	return json.Marshal(p.Value)
}
