// Generated by tools/generate-protocol.mjs from schemas/protocol/v2/spec.json.
// Do not edit manually.

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: &str = "2.0";
pub const PROTOCOL_VERSION_NUMBER: u32 = 2;
pub const SCHEMA_VERSION: u32 = 2;
pub const METRIC_SEMANTICS_VERSION: u32 = 1;
pub const DEFAULT_MAX_BATCH_EVENTS: u32 = 500;
pub const DEFAULT_MAX_BATCH_BYTES: u32 = 1048576;
pub type UInt64String = String;
pub type DecimalString = String;
pub type HmacSha256 = String;
pub type Base64Url32 = String;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "model_usage_recorded")]
    ModelUsageRecorded,
    #[serde(rename = "cost_recorded")]
    CostRecorded,
    #[serde(rename = "session_started")]
    SessionStarted,
    #[serde(rename = "session_ended")]
    SessionEnded,
    #[serde(rename = "turn_started")]
    TurnStarted,
    #[serde(rename = "turn_completed")]
    TurnCompleted,
    #[serde(rename = "tool_invoked")]
    ToolInvoked,
    #[serde(rename = "skill_invoked")]
    SkillInvoked,
    #[serde(rename = "code_changed")]
    CodeChanged,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AckResult {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "discarded")]
    Discarded,
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "invalid")]
    Invalid,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Accuracy {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "derived")]
    Derived,
    #[serde(rename = "correlated")]
    Correlated,
    #[serde(rename = "estimated")]
    Estimated,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TimeSource {
    #[serde(rename = "source_record")]
    SourceRecord,
    #[serde(rename = "prior_record")]
    PriorRecord,
    #[serde(rename = "file_mtime")]
    FileMtime,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CostSource {
    #[serde(rename = "provider_reported")]
    ProviderReported,
    #[serde(rename = "calculated_price")]
    CalculatedPrice,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TurnTrigger {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "subagent")]
    Subagent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SessionEndReason {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AckErrorCode {
    #[serde(rename = "outside_window")]
    OutsideWindow,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "future_event_time")]
    FutureEventTime,
    #[serde(rename = "unsupported_version")]
    UnsupportedVersion,
    #[serde(rename = "schema_invalid")]
    SchemaInvalid,
    #[serde(rename = "hash_mismatch")]
    HashMismatch,
    #[serde(rename = "negative_count")]
    NegativeCount,
    #[serde(rename = "unknown_field")]
    UnknownField,
    #[serde(rename = "duplicate_key")]
    DuplicateKey,
    #[serde(rename = "dependency_expired")]
    DependencyExpired,
    #[serde(rename = "internal_retryable")]
    InternalRetryable,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ModelRef {
    pub provider_id: String,
    pub model_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillRef {
    pub skill_key: Base64Url32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct UsagePayload {
    #[serde(rename = "token_total")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_total: Option<UInt64String>,
    #[serde(rename = "input_context_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_context_tokens: Option<UInt64String>,
    #[serde(rename = "output_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<UInt64String>,
    #[serde(rename = "cache_read_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<UInt64String>,
    #[serde(rename = "cache_write_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<UInt64String>,
    #[serde(rename = "reasoning_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<UInt64String>,
    #[serde(rename = "request_count")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_count: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CostPayload {
    pub units: UInt64String,
    pub currency: String,
    pub source: CostSource,
    #[serde(rename = "price_basis_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_basis_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coverage: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CodePayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub added: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub removed: Option<UInt64String>,
    #[serde(rename = "file_touch_count")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_touch_count: Option<UInt64String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActivityPayload {
    #[serde(rename = "duration_ms")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trigger: Option<TurnTrigger>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<SessionEndReason>,
    #[serde(rename = "tool_category")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_category: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ContextPayload {
    #[serde(rename = "parent_session_key")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_session_key: Option<Base64Url32>,
    #[serde(rename = "tool_call_key")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_key: Option<Base64Url32>,
    #[serde(rename = "scope_started_at")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_started_at: Option<UInt64String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coverage: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MetaPayload {
    pub accuracy: Accuracy,
    #[serde(rename = "time_source")]
    pub time_source: TimeSource,
    #[serde(rename = "safe_tags")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe_tags: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<UsagePayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost: Option<CostPayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<CodePayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub activity: Option<ActivityPayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<ContextPayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<MetaPayload>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventEnvelope {
    pub event_id: Base64Url32,
    pub fact_key: Base64Url32,
    pub fact_revision: UInt64String,
    pub schema_version: u32,
    pub metric_semantics_version: u32,
    pub harness_id: String,
    pub event_type: EventType,
    pub occurred_at: UInt64String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skill: Option<SkillRef>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_key: Option<Base64Url32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_key: Option<Base64Url32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_scope_key: Option<Base64Url32>,
    pub payload: EventPayload,
    pub content_hash: Base64Url32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TelemetryEventsRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub events: Vec<EventEnvelope>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EventAck {
    pub event_id: Base64Url32,
    pub content_hash: Base64Url32,
    pub result: AckResult,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<AckErrorCode>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TelemetryEventsResponse {
    pub request_id: String,
    pub server_time_ms: UInt64String,
    pub acks: Vec<EventAck>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TelemetryCapabilities {
    pub protocol_version: u32,
    pub supported_schema_versions: Vec<u32>,
    pub supported_metric_semantics_versions: Vec<u32>,
    pub max_batch_events: u32,
    pub max_batch_bytes: u32,
    pub server_time_ms: UInt64String,
    pub event_receive_lower_bound_ms: UInt64String,
}

